### ISSUE TITLE
Update Summit page with content and such!

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#106]
It's not real unless there's a website for it

At http://opensourcedesign.net/summit/

**Comment by raghunayyar** [comment]
If we have the content, I can get this up in a couple of hours. :)

**Comment by simonv3** [comment]
I think as far as content goes, the logo from https://github.com/opensourcedesign/organization/issues/57#issuecomment-283946644

(ping @elioqoshi for the svgs)

And then with the dates

October 13 - 18th. 

Details TBC

**Comment by elioqoshi** [comment]
Here we go:
https://github.com/uracreative/works/tree/master/OSD%20Summit

**Comment by aryasoni98** [comment]
I would like to work on that page . Redesign Summit2020 page.

**Comment by Erioldoesdesign** [comment]
@aryasoni98 I think this issue should be closed as it was about the 2018 summit and I'll look at creating a new issue here about a 'Next summit TBC' page.
