### ISSUE TITLE
Wrong name for 'rate'/'compensation' field 

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/opensourcedesign.github.io#115]
Use 'rate' instead of 'compensation' in the Job Form. New PRs and files created with 'compensation' (since 2017-02-09), while all the old jobs are using 'rate'. The layout uses rate, see 
<img width="1008" alt="rate" src="https://cloud.githubusercontent.com/assets/629552/25672260/7c207bd4-303b-11e7-9b70-aa4b83b7cbbc.png">

**Comment by evalica** [comment]
I think this was a bug also in the past.  Not sure what changed recently.

**Comment by bnvk** [comment]
Fixed this in 74da4c4ca0c55af88284ef3716205be7e757fc81 thanks @evalica
