### ISSUE TITLE
Make "Activity Feed" on homepage uber user friendly

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#12]
In pull req #11 I have introduced the idea of an activity feed. However, currently it's just the activity feed of this one repo- ideally it will encompass all repos and do some sort of intelligent "filtering" to only show highly understandable items.

**Comment by Erioldoesdesign** [comment]
@bnvk was the intention of this to 'display' all repo activity somewhere on the website? Unsure if that is really needed? especially since we are not that active here on github much consistently.

Can I close this?

**Comment by bnvk** [comment]
Thanks for tidying up from half a decade ago ;)

> @bnvk was the intention of this to 'display' all repo activity somewhere on the website?

That was the goal, but like you say it's not needed anymore due to low activity on Github.

> we are not that active here on github much consistently.

Yeah feel free to close!
