### ISSUE TITLE
Add link to the summit. 

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#120]

**Comment by pdurbin** [comment]
Yeah, as I noted at https://botbot.me/freenode/opensourcedesign/msg/89077686/ the events page is fairly out of date at this point.

**Comment by pdurbin** [comment]
@simonv3 @jancborchardt @belenbarrospena currently http://opensourcedesign.net/events/ says, "There are no upcoming events" and I just created https://github.com/opensourcedesign/events/pull/79 to fix this. Can you please take a look? Thanks!

**Comment by evalica** [comment]
Is this issue about having a link in the global menu for the Summit? or the Summit event done by pdurbin is enough?

**Comment by pdurbin** [comment]
I made another pull request at https://github.com/opensourcedesign/events/pull/80 to fix the links in my previous pull request.

**Comment by bnvk** [comment]
Closing this as the Summit is now done!
