### ISSUE TITLE
Directly use fonts from repository instead of calling googleapis

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/opensourcedesign.github.io#121]
See https://github.com/opensourcedesign/opensourcedesign.github.io/blob/6050e64bbd541c92ae1155e8c6b1990d554cdd3d/_includes/head.html#L10-L11, we should use the fonts from in the /fonts folder instead.

**Comment by bnvk** [comment]
Fixed in e7c8a6f4771d16e849c29fb0a234f078f40c332e and 061d2536830768b3e4c5725e41885be56569278f
