### ISSUE TITLE
posting a job says markdown is allowed, but it's not rendered

### ISSUE THREAD

**Issue by boneskull** [opensourcedesign/opensourcedesign.github.io#128]
Hi, discovered this today.  Maybe it needs to be more clear about *which fields* Markdown is allowed in, or simply just enable markdown for all fields?

![image](https://user-images.githubusercontent.com/924465/31089482-27e79e22-a759-11e7-833f-4d9dbea0a106.png)

I think this can be done via [a client-side lib](https://www.npmjs.com/package/markdown-it) if you wanted to go that route...

**Comment by simonv3** [comment]
We could definitely use a client side lib for this. It might be the easiest. I'm afraid how frontmatter works is a bit of a limitation here. It's been an issue for a while, but I haven't thoroughly looked into it. Is that something you'd want to look into @boneskull?
