### ISSUE TITLE
"our goals" links to a 404 (/about/) from homepage

### ISSUE THREAD

**Issue by pdurbin** [opensourcedesign/opensourcedesign.github.io#141]
If you click "our goals" at http://opensourcedesign.net you get a 404 at http://opensourcedesign.net/about/

**Comment by simonv3** [comment]
Funny, cause "goals" exists: http://opensourcedesign.net/goals/

**Comment by bnvk** [comment]
Yah, oversight on my part (forgot it links there). Now fixed.
