### ISSUE TITLE
Specify certain pages as "Uneditable"

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#146]
With the integration of the edit page buttons (as seen here), which is now on each page...

![osd-edit-source-links-2](https://user-images.githubusercontent.com/48677/31679068-501341f8-b370-11e7-8b20-62fd4bbae3de.png)

...certain pages probably should not be editable via the [Prose editor](https://edit.opensourcedesign.net) as they will have HTML, Jekyll logic, and can seriously break the site if they are edited wrong. Some examples of these pages are:

- 404.html
- index.html
- articles.html

This should be simple enough by adding the file to the Prose config excludes, and then a Jekyll var in each page, that either displays or hides the `Edit this page` link.

**Comment by simonv3** [comment]
OMG the prose integration is awesome.

**Comment by evalica** [comment]
Or we could define a CSS class that hides that section and make sure the pages are using the class.

**Comment by bnvk** [comment]
@evalica sure, I don't see a strong argument for or against CSS class vs. just not displaying the HTML in the template. Regardless, we need to add value to FrontMatter of "uneditable" pages.

**Comment by RDIL** [comment]
edit.opensourcedesign.net is down, I'm going to close this in favor of removing prose.
