### ISSUE TITLE
Styling on job form thank you page is broken

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#148]
Probably because the bootstrap stuff was moved recently?

http://opensourcedesign.net/jobs/thank-you/

https://github.com/opensourcedesign/jobs/blob/master/thankyou.html

**Comment by bnvk** [comment]
Was because that file (for some inexplicable reason) did *not* have the `layout: default` value decalred in Front-Matter and instead had the whole HTML page...

**Comment by simonv3** [comment]
ah cool! possibly because it was moved over from a stand-alone repo.
