### ISSUE TITLE
Replace hardcoded URLs to site in pages and templates

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#151]
Currently, in throughout the website Jekyll templates and pages, the website URL

```
http://opensourcedesign.net
```

Is hardcoded. We should make use of Jekyll variables, so as to make developing locally, a stagging server, etc... all work well. Thus, we should replace that value with 

```
{{ site.url }}
```

Which then gets drawn from [_config.yml](https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/_config.yml) values.

**Comment by aaqaishtyaq** [comment]
hey, @bnvk since no one is currently working/assigned to this issue, I would like take up the task.

**Comment by bnvk** [comment]
@aaqaishtyaq go for it :+1:
