### ISSUE TITLE
On job form qualify what free / open source means.

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#157]
We can do that by providing a link or by adding an asteriks, or some other format, but I can see how it leads to confusion. https://github.com/opensourcedesign/jobs/pull/260

**Comment by patdavid** [comment]
What about "Free/Libre and Open Source"?

**Comment by patdavid** [comment]
What about "Free/Libre and Open Source"?

**Comment by patdavid** [comment]
What about "Free/Libre and Open Source"?

**Comment by simonv3** [comment]
I think even then we'll need to provide a friendly "here's what that means". It doesn't mean _we_ have to write it, it should just exist.

**Comment by evalica** [comment]
The problem come from the phrase "If you work on a free / open source project and you need..." found on the [job form](http://opensourcedesign.net/jobs/job-form/). 
Maybe the "free" part needs a better definition, or maybe it was understood as "if you worked on something free in your life, but now you need some design work". We need to state that the design work will be done for OS projects, no matter of the affiliation of the submitter.

**Comment by patdavid** [comment]
I would imagine a [link to the definition of Free Software](https://www.gnu.org/philosophy/free-sw.en.html) might be a good start.

Should it be noted in some fashion, "Free as in speech" in particular?  
Or only "Free as in speech **and** beer"?

I'm personally in favor of both, but I don't begrudge someone an opportunity to monetize an otherwise Free/Libre/Open project, as long as the sources are available under a good license.

I did fork the site quickly to check, but I'm not sure where the job posting page is located - any pointers?

**Comment by evalica** [comment]
@patdavid the job form is located the the jobs repo, see https://github.com/opensourcedesign/jobs/blob/master/job-form.html

**Comment by jdittrich** [comment]
I currently see two options: 

* providing an asterisk, [link](https://en.wikipedia.org/wiki/Free_software) etc. giving further explanation
* Use only *open source* as term.

I like the free-as-in-freedom thing and all, but the term has not the best "usability" (misunderstandings) and I wonder if only using *open source* as bad consequences in practice.

**Comment by patdavid** [comment]
1. I was going to take a pass at changing the term to "Free/Libre and Open Source".
2. Make it a link (+ superset asterisk/footnote) to the bottom of the page where the term "Free" could be expanded on to be clearer.
3. Make the hover text say something like "Free as in speech" or something to that effect.

Would that be helpful?

**Comment by simonv3** [comment]
That sounds good to me! Thanks @patdavid.

**Comment by patdavid** [comment]
Unless there's something more to tweak or discuss, I'm going to close this issue.

**Comment by simonv3** [comment]
Thanks again!

**Comment by patdavid** [comment]
No problem!  I know I've been busy, but I really do intend to help out more where I can (and this was relatively simple).
