### ISSUE TITLE
Better explain what design is, and what design we're talking about specifically.

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#16]
Aside from the whole "What is design" and "What is user experience design" existential crisis, it would be sort of nice to get a rough outline of how we define design.

Is it visual? Is it aesthetic? Is it user experience? 

Sparked by: http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-05-24#i_3636466

**Comment by GarthDB** [comment]
![no idea](http://www.reactiongifs.com/r/ihniwid.gif)

**Comment by simonv3** [comment]
*Design is Innovation*

**Comment by GarthDB** [comment]
Design is problem solving.

![](https://media.giphy.com/media/Ra7IydVtYkxdm/giphy.gif)

**Comment by duythien** [comment]
Nice issue:)

**Comment by simonv3** [comment]
621 mathematical incarcerations and counting https://twitter.com/cylonvalley

**Comment by GarthDB** [comment]
Seems about right.
![image](https://cloud.githubusercontent.com/assets/125516/11344345/d1a29050-91cd-11e5-9160-6695240ac55c.png)

**Comment by GarthDB** [comment]
BTW, this is how we should recruit more designers for open source stuff.

**Comment by jancborchardt** [comment]
Of course we can explain it with high-level general words, but that will help little in making it more understandable.
From what we work on and what we did so far, we focus on interface/interaction design of software products. As an extension it is UX design (cause this term is used universally anyway these days) and branding as well.

What it’s not, at least at the moment
* hardware design (maybe in the future)
* service design
* fashion design
* database design
* …

**Comment by simonv3** [comment]
Thanks for bringing it back on topic @jancborchardt. I think the confusion comes from open source developers who are are curious about the term design in that you could use it for database design etc. 

Just saying user experience and interface design will clear that up probably.

**Comment by jdittrich** [comment]
> Just saying user experience and interface design will clear that up probably.

makes sense to me.

**Comment by GarthDB** [comment]
For mobile, web, desktop? doesn't matter? Interactive?

**Comment by jancborchardt** [comment]
Of software products for web, mobile and desktop, yes. And yeah, interaction design.

@simonv3 @jdittrich yup!

**Comment by bnvk** [comment]
Closing as this is inactive and we've better outlined our purpose and mission elsewhere!
