### ISSUE TITLE
Job rendering broken

### ISSUE THREAD

**Issue by MichaelMure** [opensourcedesign/opensourcedesign.github.io#166]
I made a job description: https://github.com/opensourcedesign/jobs/pull/289
This is the result: http://opensourcedesign.net/jobs/jobs/2018-02-06-ux-ui-design-help-needed-for-a-new-file-sharing-project

The description is missing on the website and the "how to apply" is badly formatted.

**Comment by simonv3** [comment]
Thanks for making this ticket Michael! 

This is strange - the description should have been put in the "content" of the markdown file. I wonder if there's something wrong with how that gets manipulated by staticman. 

As for the how to apply button text, I want to note that's also mentioned here: https://github.com/opensourcedesign/opensourcedesign.github.io/issues/128

**Comment by eupiteco** [comment]
As you can see above, this issue has been recently mentioned on another job PR, I'm copying what I replied there.

---
It seems that it is trying to mix MD and JS escape sequences but there is misinterpretation when the form is submitted, probably something with the @staticmanapp config.
The `[“katharina.nocun@posteo.de”, “* https://fsfe.org/\r\n* https://publiccode.eu/”]` line is a array with two strings in it: 1 - `“katharina.nocun@posteo.de”` 2 - `“* https://fsfe.org/\r\n* https://publiccode.eu/”`
The second string should be outputted like this, a MD list:
```
* https://fsfe.org/
* https://publiccode.eu/
```
The `\r` and `\n` are escape sequences for carriage return and line feed respectively. What is happening is that the form is wrapped up in JS that is not being iterpreted so the HTML page get a raw JS output as it is, maybe the ideal ouput could be something like

**How to apply:**
katharina.nocun@posteo.de
* https://fsfe.org/
* https://publiccode.eu/
 
I'm still quite a n00b to JS but eventually Il wil take a look at this, maybe the one who coded the jobs section knows where the bug could be.

**Comment by eupiteco** [comment]
Answering to @ei8fdb on the original [PR thread](https://github.com/opensourcedesign/jobs/pull/327)

>@eupiteco thanks for the explanation. Is there a specific change we can make to fix it in the meantime?
I'm happy to make some PRs to fix it if it helps.

I think that a `join()` method can be useful to output the strings without the array, [docs here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join). Then you need to handle the `\r` and ` \n` escaping sequences, my guess is that the `join()`will take car of that.

**Comment by eupiteco** [comment]
Locally the job rendering is working, follows two screen captures as an example

*Local server from the repo* 
![local](https://user-images.githubusercontent.com/972245/45665602-0098e800-bae8-11e8-90de-f5141847bc47.png) 

*Same job on the actual site* 
![web](https://user-images.githubusercontent.com/972245/45665608-0393d880-bae8-11e8-9c82-9324f393c486.png) 

Anyone knows thy is this happening?

**Comment by eupiteco** [comment]
Reopening since the prod site is not following the dev changes. My guess is that the PR must be done in the Jobs repo, not this one, does it make sense?

**Comment by keunes** [comment]
I published a job, and I'm very grateful this platform is set up & maintained. But the 'How to apply' really needs an improvement, so many thanks @jancborchardt and @eupiteco for working on this! Hope it gets fixed soon :)

**Comment by SaptakS** [comment]
I will take a look into this and come up with some solutions.
