### ISSUE TITLE
Missing menu entries when going to Jobs, Events

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/opensourcedesign.github.io#167]
Expected
<img width="1183" alt="expected" src="https://user-images.githubusercontent.com/629552/36148187-bb66fdae-10c3-11e8-8240-e82e1d559b73.png">

Menu on Jobs
<img width="1222" alt="jobs" src="https://user-images.githubusercontent.com/629552/36148191-c22eb4d8-10c3-11e8-8260-5e80aa398e64.png">

Menu on Events
<img width="1146" alt="events" src="https://user-images.githubusercontent.com/629552/36148201-c688bfa6-10c3-11e8-93fb-7430c0c2e388.png">

Missing: some entries + the logo

**Comment by evalica** [comment]
After: 
Job
<img width="1203" alt="afterjobs" src="https://user-images.githubusercontent.com/629552/42373430-88252130-811d-11e8-8b36-f51fdc397615.png">

**Comment by elioqoshi** [comment]
Thanks @evalica !
