### ISSUE TITLE
Missing Affiliation page on the website

### ISSUE THREAD

**Issue by evalica** [opensourcedesign/opensourcedesign.github.io#168]
We don't show anywhere on the website the affiliations we have 
<img width="955" alt="affiliations" src="https://user-images.githubusercontent.com/629552/36148304-30f67ec8-10c4-11e8-98ee-54d7734f8224.png">

**Comment by aaqaishtyaq** [comment]
Shall I create a new page and add a link to nav bar?

**Comment by jancborchardt** [comment]
This should be directly on bottom of the main page. We also discusser at the Summit that we have too many subsites already. :)

@aaqaishtyaq I have a branch locally which has the logos of organizations which supportef us in different ways. I can push that when at the computer, would you be interested in then adding it to the main page? :)

**Comment by RDIL** [comment]
Status update?

**Comment by aaqaishtyaq** [comment]
@jancborchardt Can you push your local branch, I'll start from there

**Comment by AnXh3L0** [comment]
Fixed by #243
