### ISSUE TITLE
Proposed renewal logo for "OPEN SOURCE DESIGN"

### ISSUE THREAD

**Issue by k-syusteem** [opensourcedesign/opensourcedesign.github.io#175]
Hello! I have designed a logo for "OPEN SOURCE DESIGN", I hope you are interested. Give your assessment so I can solve a problem related to the logo you want for "OPEN SOURCE DESIGN".

![web](https://user-images.githubusercontent.com/38687140/40282106-363220f6-5c94-11e8-9c5e-6006718b0f7f.png)

![01](https://user-images.githubusercontent.com/38687140/40282108-3e1dae3e-5c94-11e8-8332-f9ac54dfb00c.png)

![02](https://user-images.githubusercontent.com/38687140/40282110-45f83a66-5c94-11e8-9a4c-7ec8444903b0.png)

@k-syusteem

**Comment by ei8fdb** [comment]
Hi @k-syusteem thanks for the submission. Can you give a little bit of information on how you decided on it? Thanks!

**Comment by k-syusteem** [comment]
### Hi @ei8fdb!

I just designed this logo that has the basic concept of "Design" "Pencil" "OpenSource" and uses the eye symbol as a designer's precision in doing a design.

**Comment by raghunayyar** [comment]
but why are renewing the logo again?

**Comment by jdittrich** [comment]
@k-syusteem Is this a submission for [this discussion](https://github.com/opensourcedesign/organization/issues/68)? Or some other discussion/issue? 

I suppose me, @ei8fdb and @raghunayyar did not expect anyone to submit a new logo so we might be a bit confused what made you rework it. I appreciate the idea, but I don't know what to do with it, since I don't see a reason to change the current logo.

**Comment by k-syusteem** [comment]
@jdittrich No, I just suggest and I'm happy to do this. Thanks!

**Comment by jancborchardt** [comment]
@k-syusteem I recommend to go to the Open Source Design Job Board: https://opensourcedesign.net/jobs/ – and look for a project which actually looks for a new logo. :) Then spend some time getting to know the project and talk with the people what they are looking for, and then you can go through logo proposal iterations. :)
