### ISSUE TITLE
Discourse integration in Job Board doesn’t seem to work when site is accessed over https

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/opensourcedesign.github.io#176]
Compare http (comments show on bottom):
http://opensourcedesign.net/jobs/jobs/2017-12-30-hospitalized-patient-management-module-mockups

And https (comments do not show):
https://opensourcedesign.net/jobs/jobs/2017-12-30-hospitalized-patient-management-module-mockups

@simonv3 @ei8fdb @AnXh3L0 if you have any idea here.

**Comment by AnXh3L0** [comment]
I will check the repos and the script to check where's the problem, but I suspect it's because the script is served via http meanwhile the website works with HTTPS (doesn't load HTTP scripts). 

The solution might be as simple as adding an "s" to the http link but I'll check and let you know soon.

**Comment by jancborchardt** [comment]
Opened a pull request which _could_ solve it at https://github.com/opensourcedesign/jobs/pull/316

**Comment by jancborchardt** [comment]
Works! :)
