### ISSUE TITLE
Remove position "UX designer (contracted)"

### ISSUE THREAD

**Issue by kelson42** [opensourcedesign/opensourcedesign.github.io#177]
Hi, I'm an admin of the Kiwix project. We have achieved to found someone for https://opensourcedesign.net/jobs/jobs/2018-02-17-ux-designer-contracted. Thank you for your help on this. May you please remove the job offer?

**Comment by elioqoshi** [comment]
To clean up a bit on older issues I went ahead and edited it. Closing this
