### ISSUE TITLE
Opensourcedesign.net Homepage Article View 

### ISSUE THREAD

**Issue by dmichl** [opensourcedesign/opensourcedesign.github.io#185]
I noticed a few blog posts have disappeared off the homepage under the **Articles Header**.  I had recently pushed two articles (one from 12/14/17 which never showed and one from our recent meetup 7/12/18) both are not publishing but older articles are now also missing. The list from what I remember was:

11/22/16 Designers in open Source: Julia
3/27/17 Open source design needs better collaboration tools
10/31/17 Open source design first NYC meetup
11/9/17 open source Design NYC 11-09 meetup Recap (this is the only one still showing)
12/14/18 OSD meetup recap 
7/12/18 OSD meetup recap 

Also if you go to the articles page there are two July 29, 2018 subheaders that are empty (which I believe is when I pushed my changes on Github). Please have a look and let me know if this is being caused by something in my markdown. Thank you!!

**Comment by jancborchardt** [comment]
cc some people who might also know a bit about the Markdown or Jekyll. ;) @ei8fdb @evalica @AnXh3L0 

Will try to debug too, but a first look didn’t bring anything up yet.

**Comment by ei8fdb** [comment]
@jancborchardt I greatly appreciate that you think I know enough about at markdown and in general coding! But I am not knowledgable enough :(

**Comment by Jc-L** [comment]
@dmichl Is this still an open issue ? All articles seem visible under the _Articles_ page.

**Comment by dmichl** [comment]
> @dmichl Is this still an open issue ? All articles seem visible under the _Articles_ page.

yes still open - right now only dec 2017 and july 2018 are showing listed instead of all the other articles I mentioned above.

**Comment by Jc-L** [comment]
The `index.html` file is configured to display only 3 articles:

            {% for post in site.posts limit:3 %}

Displaying all articles/posts will unbalance the page; I can change the value to another one and add a 'See all articles' link as well. Please suggest a proper value.

**Comment by RDIL** [comment]
I’d go for 4, see all sounds good enough

**Comment by dmichl** [comment]
> The `index.html` file is configured to display only 3 articles:
> 
> ```
>         {% for post in site.posts limit:3 %}
> ```
> Displaying all articles/posts will unbalance the page; I can change the value to another one and add a 'See all articles' link as well. Please suggest a proper value.

 I'm ok with leaving three articles as is - it prevents the page from getting too text heavy with the other two columns (events/jobs). 
With that said, happy to close this issue! Thanks for the help!
