### ISSUE TITLE
"closed" vs "resolved" for job status

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/opensourcedesign.github.io#186]
In some of our job posts which are finished we use the status "closed", in others the status "resolved".

What is the correct one we should use? It doesn’t seem to correlate with the values in the config.yml either: https://github.com/opensourcedesign/jobs/blob/master/_config.yml#L18-L26

@m1guelpf @AnXh3L0 what do you think?

**Comment by ei8fdb** [comment]
Since the request is a job "post", to me "closed" seems to make sense.

"Resolved" sounds like it's an issue. It's also a bit "technical".

Obviously, just an IMHO. :)

**Comment by evalica** [comment]
"Closed" as stated also in https://github.com/opensourcedesign/opensourcedesign.github.io/issues/70#issuecomment-270925924

**Comment by ei8fdb** [comment]
Do we want to get more input? 

Just wondering. I'll happily update the jobs ads that aren't looking anymore to whatever we decide on.

**Comment by belenbarrospena** [comment]
I think we all agree "closed" is better. Make it so! :p

**Comment by ei8fdb** [comment]
🖖

**Comment by m1guelpf** [comment]
closed! :p

**Comment by jancborchardt** [comment]
Thanks a lot for the input! :) So should we also change the config.yml, or what is that actually for?
