### ISSUE TITLE
Ruby Sass is deprecated

### ISSUE THREAD

**Issue by eupiteco** [opensourcedesign/opensourcedesign.github.io#192]
Got this after `$ bundle install` :
```
Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
```
My guess is editting the gem configfile and replacing `'sass'` with `'sassc'` will do the job but not so sure about eventual conflicts it may bring.

Can anyone with more experiepnce/knowledge about this project tell what is necesary to update the sass gem?

**Comment by jancborchardt** [comment]
@eupiteco did you try locally what you suggest, and did it work out?

@Anxh3l0 what do you think? For the new design would you use Sass and would @eupiteco's fix work?

**Comment by eupiteco** [comment]
The solution seems to be pretty straight forward, as seen here http://sass.logdown.com/posts/7081811. The problem is I did not found where is the config file for the Ruby packagers :sweat_smile:, can someone guide me through the files?

**Comment by jancborchardt** [comment]
I would have thought there’s some more info in the Gemfile or Rakefile, but can’t find any.

Quickly searched for the relation to Jekyll and found this issue recommending sassc-ruby: https://github.com/jekyll/jekyll-sass-converter/issues/74
@eupiteco is that a good pointer maybe? :)

**Comment by RDIL** [comment]
I can port the SCSS if needed

**Comment by jancborchardt** [comment]
@AnXh3L0 @dmichl @ei8fdb and others from @opensourcedesign/website – what do you think?

**Comment by patdavid** [comment]
Is there really a need for SASS?

**Comment by jancborchardt** [comment]
I guess especially with CSS4 variables, SASS is not really needed so much. @AnXh3L0 @elioqoshi @dmichl @evalica @ei8fdb @simonv3 what do you think?

@RDIL cause in that case a pull request to replace the SASS with the generated CSS would be cool!

**Comment by RDIL** [comment]
On it.

**Comment by RDIL** [comment]
@jancborchardt problem: I can't seem to find where the variables used in the Sass have their value held.

**Comment by evalica** [comment]
CSS variables and Sass variables have different scopes. CSS Variables should be used when the value changes a lot and needs to adapt depending on the element. Sass variables should be used for constants. 
So, depending on the case, we could indeed replace Sass variables with CSS variables, with the mention that CSS variables have more limited browser support (again, depends what we consider our target to be).

**Comment by RDIL** [comment]
I don't think we would need CSS variables because if I knew the values of the sass variables we could just put the raw values

**Comment by evalica** [comment]
We are using mostly the Bootstrap defined variables from https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/_sass/vendor/_bootstrap.variables.scss 
Changing those to CSS variables means a lot of work.

**Comment by RDIL** [comment]
I'm going to remove them and replace them with their actual values if you don't mind.

**Comment by evalica** [comment]
Changing variables to actual values for me means a step behind. Instead of reusing values and be able to change them, because of conflict we will lose these benefits. 
I think the fix here is just to update or find a replacement for the gem.

**Comment by RDIL** [comment]
I'll try to replace it.

**Comment by RDIL** [comment]
It looks like the only alternative is Dart Sass, I don't see how that would work however.  I think we need to stay on the current gem.

**Comment by patdavid** [comment]
Ah, I should have looked closer.  I apologize.  If using a big framework like bootstrap, it's probably best to not muck around there and instead switch to supporting the required gems to update.

**Comment by RDIL** [comment]
I'm not very good with ruby/gems, so I'm going to step out on this one.

**Comment by eupiteco** [comment]
Found  it: our gemfile required the `github-pages` gem, witch required `jekyll-sass-converter` wich finally required `sass`. Good new is that eht sass/sassc issue is [already solved](https://github.com/jekyll/jekyll-sass-converter/pull/75) within `jekyll-sass-conveter`. I just ran `bundle install` with no warnings nor problems.
That said, I am closing this issue. :tada:

**Comment by ei8fdb** [comment]
I think I understand the significance of this. Muito obrigado @eupiteco. 👍 🎉
