### ISSUE TITLE
edit.opensourcedesign.net

### ISSUE THREAD

**Issue by signalwerk** [opensourcedesign/opensourcedesign.github.io#207]
On Line 14 of the [README.md](https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/README.md) is a link to [edit.opensourcedesign.net](http://edit.opensourcedesign.net/) but there is just a default Apache2 Server page.

**Comment by evalica** [comment]
I think those links are just there as bookmarks. I didn't add them or used them, so not sure about them. but makes sense that they display what tools were used to build the website and provide easy access. Let's see what others think. Thanks for the report

**Comment by jancborchardt** [comment]
@signalwerk edit.opensourcedesign.net was a hosted Prose if I remember correctly. We should ideally not rely on external tools and Github has this nice online editing functionality we can use. :)

So a pull request would be great! The relevant pages would have to be linked to the "edit-mode" version of the file on Github. Or if that's not possible just the file itself, then people can edit it using the pen in the top right. :)

**Comment by RDIL** [comment]
Closing in favor of the removal of `Prose`.
