### ISSUE TITLE
Activity feed comments

### ISSUE THREAD

**Issue by Xaviju** [opensourcedesign/opensourcedesign.github.io#23]
In homepage, users writing 'clever comments' is a fabulous feature. However, I am not able to see the comment. It links to their user profile instead of the comment. Should we add the comment or, at least, the comment link?

**Comment by jancborchardt** [comment]
Yeah, I’d say the action should be linked to provide context, rather than the person.

**Comment by simonv3** [comment]
The issue here was that there was some different nesting for each type of github "event" in the api, and figuring that out was a bit more work than was possible at the time. It shouldn't be hard to implement, you just have to figure out what the link structure is and do it :).

**Comment by duythien** [comment]
@Xaviju I think it have completed at this PR https://github.com/opensourcedesign/opensourcedesign.github.io/pull/29

**Comment by simonv3** [comment]
Yep, this looks like it works on http://opensourcedesign.net/. Thanks @duythien :)

**Comment by duythien** [comment]
Awesome :)
