### ISSUE TITLE
Broken Link in Footer

### ISSUE THREAD

**Issue by vinitshahdeo** [opensourcedesign/opensourcedesign.github.io#235]
The **`Chat With Us`**  [link](http://chat.opensourcedesign.net/) in footer seems to be broken in [`events`](https://opensourcedesign.net/events/) page.

<img width="1246" alt="Screenshot 2019-05-13 at 3 06 57 AM" src="https://user-images.githubusercontent.com/20594326/57588070-5d8c5700-752c-11e9-96f2-e22419872905.png">

**Comment by jancborchardt** [comment]
Ah, good catch. I thought there was already a unified footer? @RDIL @Jc-L @AnXh3L0 do you know anything about this?

We also discussed a lot in the past that we would like to move the events and jobs repos ideally into this repository so we have one single repo for the website. My knowledge of Jekyll is not proper enough for this – maybe you have ideas? :)

**Comment by RDIL** [comment]
That second idea is more of a long term thing, so that will take some time.  I will look into this however.

**Comment by Jc-L** [comment]
> I thought there was already a unified footer?

The footer is unified on a per-site base, but not with the *event* and *jobs* sub-sites. I just checked and the headers, menus, and event fonts are inconsistent. These sub-sites use some kind of forms however, and I do not know exactly how this is managed.
@RDIL We can have a discussion on this to see how to move forward.
