### ISSUE TITLE
Add conferences section to opensourcedesign.net

### ISSUE THREAD

**Issue by ei8fdb** [opensourcedesign/opensourcedesign.github.io#250]
## Description
Adding a section to the opensourcedesign.net website to publicise the conferences we have been involved.

Include the logo for [FOSDEM](https://fosdem.org), [Apachecon EU](https://www.apachecon.com/) and [FOSSASIA](https://fossasia.org/).

## Proposed design
Copy the format of the affiliates, and supporters sections on the website.

**Comment by ei8fdb** [comment]
@AnXh3L0 @evalica @victoria-bondarchuk 

I'd appreciate some criticism on how suitable the logo files are. I've taken the logos from the conference websites. I had to convert FOSDEM and Apachecon logo to SVG.

**Comment by jancborchardt** [comment]
Was fixed some time ago, the conferences are now on the website. :)
