### ISSUE TITLE
Organization invites broken

### ISSUE THREAD

**Issue by RDIL** [opensourcedesign/opensourcedesign.github.io#253]
Recently, the automatic organization invite system that OSD used was taken down, and the creator has expressed that he doesn’t plan to bring it back anytime soon. 

As far as I can see, we have 4 options:
* Self host that solution (requires paying for server)
* Self host [Aeryn](https://github.com/moya/aeryn) - also requires server, but I think is a better solution because it requires people to contribute to an OSD project before they get the invite
* Solution like [the collective](https://github.com/collective/) - users request invites via GitHub issues in a dedicated repo (doesn’t require money, but does require people to actually triage the issues and manage inviting, which I’m willing to do)
* Or finally, the last option, make the org invite only meaning an existing members can invite new ones - this is by far the worst solution as it does seem to go against OSD’s views, but I feel like it still should get mentioned

Cc @opensourcedesign/core

**Comment by jancborchardt** [comment]
> Or finally, the last option, make the org invite only meaning an existing members can invite new ones - this is by far the worst solution as it does seem to go against OSD’s views, but I feel like it still should get mentioned

I’d actually go for this. The Github organization does not reflect _all_ of Open Source Design, so it shouldn’t be the "join" command.

We do want people to get involved in multiple ways, and yes that can include Github, but also the forum, or organizing events, doing talks, etc etc.

The main point being that whether you are part of a community is not decided by your membership in a group of that community on a specific platform, but by your general activity in that community.

**Comment by yohix** [comment]
I recommend to look on this https://github.com/github-craftwork/start-here

**Comment by RDIL** [comment]
@yohix please see https://github.com/opensourcedesign/opensourcedesign.github.io/issues/253#issuecomment-549201730 as for why that wouldn't be a good idea.  

Closing this issue for now.
