### ISSUE TITLE
Navbar responsiveness issue

### ISSUE THREAD

**Issue by Yashank18** [opensourcedesign/opensourcedesign.github.io#265]
## Issue - Navbar isn't responsive in the mobile view.
 2 Nav items aren't visible i.e ( Forum and Summit)

Screenshot Attached -
![Screenshot (113)](https://user-images.githubusercontent.com/46098062/79488917-21b11a00-8038-11ea-8f99-09c59f0bbb1f.png)
![Screenshot (111)](https://user-images.githubusercontent.com/46098062/79488968-39889e00-8038-11ea-8e66-b366f187b295.png)

**Comment by RDIL** [comment]
Sure thing!  The issue is all yours.

**Comment by Yashank18** [comment]
Thank you @RDIL 😃

**Comment by Yashank18** [comment]
@RDIL Please Check #266 .
Thank you :)
