### ISSUE TITLE
Add Facebook page

### ISSUE THREAD

**Issue by razetime** [opensourcedesign/opensourcedesign.github.io#27]
I think having a page on facebook would be useful to convey news about Open Source Design and help invite more people to Open Source Design. 
What do all of you think?

**Comment by simonv3** [comment]
I'd be down with it. If anyone wants to take action on that they should go ahead. 

You could link it to the articles page.

**Comment by jancborchardt** [comment]
Yeah, we could handle that just like the [Open Source Design Twitter](https://twitter.com/opensrcdesign). As @simonv3 said: If you want to take action, just go ahead. :)

**Comment by RaghuAllTheTime** [comment]
Ok then!

**Comment by simonv3** [comment]
@razetime Did you end up doing this? If so, could you add a link on the website?

**Comment by razetime** [comment]
Here you go: https://www.facebook.com/opensrcdesign/

**Comment by jancborchardt** [comment]
@razetime can you change the URL to the proper long form /opensourcedesign? It’s only opensrcdesign on Twitter because of the character limit.

**Comment by grahamperrin** [comment]
https://www.facebook.com/opensrcdesign/

> :exclamation: **Sorry, this content isn't available at the moment**
> The link you followed may have expired, or the Page may only be visible to an audience that you aren't in.

https://github.com/opensourcedesign/organization/issues/18#issuecomment-158934333 relates to https://www.facebook.com/opensourcedesign/ for a different Open Source Design. 

I can't find a more recent issue relating to a Facebook page for this organisation, is it no longer a channel?

**Comment by simonv3** [comment]
(That thumbs down is because of the forgotten facebook page, not at you doing that investigative work @grahamperrin).

**Comment by grahamperrin** [comment]
:-) and for anyone who wonders about the investigation, it's with regard to point (1) at https://github.com/opensourcedesign/organization/issues/68#issuecomment-291985097

Should this issue be reopened?

**Comment by simonv3** [comment]
I think we need to make some other people administrator of the facebook page who can guarantee being around a bit more often. @razetime?

**Comment by jancborchardt** [comment]
Yep. I don’t have a Facebook account, but any of the people in the core team who have should be made page admin: @bnvk @evalica @belenbarrospena @simonv3 @jdittrich @Incabell @victoria-bondarchuk @elioqoshi 

@razetime can you make sure to add them as page admins? Thanks! :)

As for the Medium instance we also have floating around which was set up by @razetime, I would say we get rid of it to promote our own articles page and as we already support a lot of proprietary platforms. What do you think?

**Comment by simonv3** [comment]
Yay, another person who doesn't use Facebook. We are legion!

**Comment by Xaviju** [comment]
I think that since we do not have enough content or time to write blog posts or generate facebook content, we shouldn't open so many fronts that will probably be most of the time empty or forgotten. Too many resources are a bit overwhelming. 
But if someone(s) have the time and initiative to be responsible for keeping it active, go for it.

**Comment by jancborchardt** [comment]
I mailed @razetime about removing the Facebook account and the Medium account too (https://github.com/opensourcedesign/organization/issues/17). :)

**Comment by bnvk** [comment]
Closing this since we are definitely not adding it to our site!
