### ISSUE TITLE
Mobile Responsive issue

### ISSUE THREAD

**Issue by Yashank18** [opensourcedesign/opensourcedesign.github.io#272]
### Screenshot - 
![Screenshot (147)](https://user-images.githubusercontent.com/46098062/80922347-1846e200-8d9a-11ea-8cea-e880f0ac504d.png)
### I would like to resolve this. Please assign it to me

**Comment by Yashank18** [comment]
@vinitshahdeo @RDIL 
Hey just wanted to check should I create a PR corresponding to this issue or I should wait for someone to assign me with the same?

**Comment by RDIL** [comment]
No need to wait for assignment.

**Comment by Yashank18** [comment]
Okay :)
