### ISSUE TITLE
Jobs Page Navbar button

### ISSUE THREAD

**Issue by Yashank18** [opensourcedesign/opensourcedesign.github.io#275]
### Steps to reproduce Issue.
* Switch to Mobile view
* Go to Job's Page
* Click on Navbar toggle button

### Screenshot
![Screenshot (158)](https://user-images.githubusercontent.com/46098062/81397743-8c400c00-9145-11ea-8b86-9f2c4e882d7c.png)

**Comment by RDIL** [comment]
This needs to be fixed downstream in the jobs repo.

**Comment by Yashank18** [comment]
Okay @RDIL  so this issue need to be transferred there?

**Comment by jancborchardt** [comment]
We’re using this repository to track all issues, since we ideally at some point also move the contents of the jobs repository in here. :) Just tagged it with "Jobs".

**Comment by Yashank18** [comment]
Okay @jancborchardt :)

**Comment by rajatgupta24** [comment]
Hi 👋 ,
I wanted to fix this bug can you please guide me and assign this to me.
Thank You

**Comment by jancborchardt** [comment]
Hi @rajatgupta24, feel free to just look into this – no assignment is needed. :)

About how to tackle this: I would recommend you compare why it works on the other pages, and why it doesn’t on the Jobs page. If something interferes with it opening, or if it actually opens but is overlapped by something maybe? We are using Bootstrap, just for information if it is a known issue. :)

**Comment by rajatgupta24** [comment]
@jancborchardt 
The classes of `div` & `ul` don't change when the button is clicked, it remains collapsed and the `main.js` that is linked in html file is showing `status = 404`.

There is no file named `main.js ` in js folder.

**Comment by rajatgupta24** [comment]
Hi, @jancborchardt I'm having trouble with this can you please guide me, this issue needs to be solved.

**Comment by AnXh3L0** [comment]
This is going to be irrelevant and fixed in the new version of the website.

**Comment by Yashank18** [comment]
This issue should be closed I guess @AnXh3L0
