### ISSUE TITLE
Allow OSD website repo to be cloned via https

### ISSUE THREAD

**Issue by amitlzkpa** [opensourcedesign/opensourcedesign.github.io#276]
Current process involves cloning the project via ssh. The setup docs suggest cloning using 
```git clone git@github.com:opensourcedesign/opensourcedesign.net```
followed by 
```./scripts/install.sh```
The process seems a little complex and not sure why we do it this way.
Would it be easier to just have the content in one place and cloned along with the repo (over https)?

**Comment by amitlzkpa** [comment]
Related discussion: https://github.com/opensourcedesign/opensourcedesign.github.io/pull/182

**Comment by SaptakS** [comment]
@amitlzkpa having looked at the script, I really feel that the best way to go about it using submodules. Then one won't have to do something like using `./scripts/install.sh`. Instead if someone cloned as `git clone --recursive git@github.com:opensourcedesign/opensourcedesign.net`, then it would also clone all the sub repos that are there. And that way, won't also need to copy all content to this repo.
And it will also allow users the flexibility to use https or git based on their choice. For users like me with ssh and GPG key enabled with Github account, cloning over https is more pain (and less secure) than cloning over git@

Does that make sense?

**Comment by jancborchardt** [comment]
Just a note regarding submodules: We should not be needing to use those, as the plan is to **Merge all repositories #236**.

Events is already merged into this one, only jobs is missing.

**Comment by SaptakS** [comment]
OKay. In that case, this issue won't make much sense separately, if everything is merged into a single repo. The make command can be used to install dependencies and then serve? But given everything will be merged in a single repo, there should be no problem cloning it via https

**Comment by amitlzkpa** [comment]
So should we continue the discussion here or carry it over to the other threads?
Looks like there's been more work on this even on other PRs.
https://github.com/opensourcedesign/opensourcedesign.github.io/pull/239

**Comment by SaptakS** [comment]
Given the discussions, if everything is being moved to this repo, then we can totally dump the script, and then the problem of cloning over https or git both should work okay. We can have a `make` command, etc. but I feel that's not related to this issue.

**Comment by amitlzkpa** [comment]
Closing this in favour of #236
