### ISSUE TITLE
Lot of space between elements in responsive design

### ISSUE THREAD

**Issue by ramneek008** [opensourcedesign/opensourcedesign.github.io#278]
![FireShot Capture 016 - Open Source Design - opensourcedesign net](https://user-images.githubusercontent.com/48586823/81829569-aa987400-9558-11ea-9f7b-6155cf19db82.png)

The central part is just full of margin

**Comment by ramneek008** [comment]
I would like to work on this issue.

**Comment by vsasvipul0605** [comment]
I would like to claim this issue and start working on this asap.

**Comment by divyabhushan** [comment]
Hi, @ramneek008 I would like to resolve this issue. Please assign it to me. Thanks

**Comment by RDIL** [comment]
No need to fight over the issue 😅.  Whoever opens a fix PR first gets it.

**Comment by ramneek008** [comment]
But i was waiting for the assignment.. I would have done it till now.. Please assign me.

**Comment by jancborchardt** [comment]
@divyabhushan @vsasvipul0605 there’s plenty more issues at https://github.com/opensourcedesign/opensourcedesign.github.io/issues – you are welcome to pick up any of those. :) And reviewing active pull requests helps a lot always!

**Comment by vsasvipul0605** [comment]
@jancborchardt thanks man for advice. I'm just a beginner and will surely look into issues and will definitely try to contribute.

**Comment by divyabhushan** [comment]
> @divyabhushan @vsasvipul0605 there’s plenty more issues at https://github.com/opensourcedesign/opensourcedesign.github.io/issues – you are welcome to pick up any of those. :) And reviewing active pull requests helps a lot always!

@jancborchardt Thanks for your reply. I will certainly contribute to enhancing this repo.
