### ISSUE TITLE
Subscribe via RSS error

### ISSUE THREAD

**Issue by Yashank18** [opensourcedesign/opensourcedesign.github.io#282]
On the Article page, there is a text button "Subscribe via RSS", I think there is some error with that button as it gives an XML file which says no data associated.
Is this behavior correct for the link or its due to some error?
* Screenshot -
![Screenshot (163)](https://user-images.githubusercontent.com/46098062/82889674-ba588500-9f68-11ea-8ca0-ce8c08d38778.png)

**Comment by RDIL** [comment]
This is intentional, this is what an RSS feed looks like.

**Comment by jancborchardt** [comment]
Yup – it seems you might not have a program installed to subscribe to feeds? Otherwise you should get prompted to subscribe somehow.

**Comment by Yashank18** [comment]
Okay okay @jancborchardt
