### ISSUE TITLE
Add link on Supporters section

### ISSUE THREAD

**Issue by aryasoni98** [opensourcedesign/opensourcedesign.github.io#284]
Eriol's edit = Looks like this issue and associated PR's are adding missing links to various logos of our supporters towards the bottom of our main webpage.

<img width="1143" alt="Screenshot 2021-06-22 at 14 52 30" src="https://user-images.githubusercontent.com/11681324/122937066-9339d600-d369-11eb-87c0-e9eca4e42af1.png">

**Comment by Erioldoesdesign** [comment]
Looks like the associated PR is closed and the new PR is https://github.com/opensourcedesign/opensourcedesign.github.io/pull/328

**Comment by JOSHI-owo** [comment]
Is anyone working on this issue?
I'm new to open source and I would like to work on this issue.

**Comment by Erioldoesdesign** [comment]
@JOSHI-owo if you would like to review https://github.com/opensourcedesign/opensourcedesign.github.io/pull/340 and add it it please go ahead 🙏

**Comment by JOSHI-owo** [comment]
@Erioldoesdesign I saw #340 . Can you please direct me to the the files to be edited.

**Comment by Erioldoesdesign** [comment]
> @Erioldoesdesign I saw #340 . Can you please direct me to the the files to be edited.

I don't know what 'files' you mean but you probably would need to branch from https://github.com/aryasoni98/opensourcedesign.github.io or https://github.com/opensourcedesign/opensourcedesign.github.io/pull/340/commits

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by MillsapTatiana-FS** [comment]
Has this issue been resolved? If not I would like to take on the task.

**Comment by Erioldoesdesign** [comment]
> Has this issue been resolved? If not I would like to take on the task.

I think this is no longer needed!
