### ISSUE TITLE
Add heading to the supporters section 

### ISSUE THREAD

**Issue by rajatgupta24** [opensourcedesign/opensourcedesign.github.io#288]
Hi,

While visiting the site i noticed that the contributor section doesn't have a heading which would be nice to have.

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/55191777/84740755-df5b7900-afa5-11ea-83d5-dd36ad8741da.png)

Thank You

**Comment by razetime** [comment]
I'm sorry, but shouldn't the section be named backers?

**Comment by jancborchardt** [comment]
@razetime as per the pull request it’s going to be "Contributors & Backers" :)  https://github.com/opensourcedesign/opensourcedesign.github.io/pull/289/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR73
