### ISSUE TITLE
Joining the Organisation

### ISSUE THREAD

**Issue by Yashpandey4** [opensourcedesign/opensourcedesign.github.io#298]
I know this isn't the right place for this, but can someone help me with the steps to Join the OpenSourceDesign Organisation? Thanks.

**Comment by RDIL** [comment]
Right now it isn't possible to join unless you contribute I believe.  This policy was recently changed so I'm not sure.

**Comment by Yashpandey4** [comment]
Can anyone give some clarity about the process then? Thanks.

**Comment by RDIL** [comment]
To quote @jancborchardt
> I’d actually go for this. The Github organization does not reflect all of Open Source Design, so it shouldn’t be the "join" command.
> We do want people to get involved in multiple ways, and yes that can include Github, but also the forum, or organizing events, doing talks, etc etc.
> The main point being that whether you are part of a community is not decided by your membership in a group of that community on a specific platform, but by your general activity in that community.

So unfortunately it isn't open for joining right now.
Sorry.
