### ISSUE TITLE
Back to Top Button

### ISSUE THREAD

**Issue by sagar-barapatre** [opensourcedesign/opensourcedesign.github.io#302]
A static back to top button is required so that user at anytime viewing this website can move to the top of website.

**Comment by Harshit564** [comment]
I can do that. Please assign it to me

**Comment by emerzon1** [comment]
I will do this unless @Harshit564 is doing it.

**Comment by jancborchardt** [comment]
@Harshit564 @emerzon1 any of you is very welcome to work on this. :) No need to be assigned to it, you can just go ahead and make the code change and propose a pull request.

**Comment by AnXh3L0** [comment]
Thanks for the suggestion, we'll include a back to top button on the new version of the site.

**Comment by im-adithya** [comment]
Working on it!
