### ISSUE TITLE
Order entries on /events/ from newest (top) to oldest (bottom)

### ISSUE THREAD

**Issue by ei8fdb** [opensourcedesign/opensourcedesign.github.io#304]
Right now the entries on https://opensourcedesign.net/events/ are from oldest to newest, as can be seen here:

![image](https://user-images.githubusercontent.com/1899506/96429938-6ee59280-11f9-11eb-9782-8866d785cfcb.png)

The ordering should be from newst (top) to oldest (bottom) to save users from 1) thinking there are no new events, 2) scrolling to the bottom to see if there are newer events.

My proposal is to just flip the entries, so newest (past) events are in the top.

I don't know how this page is constructed, so I don't know how to change it. But I'm happy to help, and review PRs.

**Comment by RDIL** [comment]
I broke this some time ago, and I spent a few hours working for a solution with no luck so far.  
I will revisit this soon.
