### ISSUE TITLE
Add SSL/TLS support to website

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#31]
Because, security. Because, privacy are good things :smiley: 

I've done this before using ~~CloudFlare~~ + Github page hosted sites. It's relatively easy and i'll look into doing it when I have a few free minutes!

Update: My thinking has changed a bit. **FUCK CLOUDFLARE**. Me (and every other Tor user) are suffering [death by a thousand CAPTCHA's](https://twitter.com/brennannovak/status/715255949003526145) daily because we believe in the right for  a free and non-surveiled internet. Thus, OSD seriously needs to consider an alternate approach! Sorry for suggesting CloudFlare and now 180'ing

**Comment by simonv3** [comment]
Thanks @bnvk!

**Comment by dominicrico** [comment]
What about using [letsencrypt.org](https://letsencrypt.org/)? It’s free, open and would fit the open source thinking :P

**Comment by simonv3** [comment]
@dominicrico Does that work when hosting on GitHub?

**Comment by dominicrico** [comment]
That's a pretty good question... Haven't check that, but they are really flexible. Will check it asap and write a comment.

**Comment by dominicrico** [comment]
Ok, have checked it and think that the cloudflare solution would be the best and easiest way to do this.

**Comment by sudheesh001** [comment]
I think Kloudsec is by far the easiest, it provides `https://` for github pages. @nubela introduced me to the tool https://kloudsec.com/github-pages/new that he created and it works perfectly, why not give this a try ?

**Comment by razetime** [comment]
@sudheesh001 Sounds really nice, but the CloudFlare solution is easier and relatively more well known.
Any more thoughts on this?

**Comment by simonv3** [comment]
I have no preference on or the other.

**Comment by bnvk** [comment]
Actually, I've considerably changed my opinion on using CloudFlare (see original comment). Let's try kloudsec :+1:

**Comment by simonv3** [comment]
Heh. Anyone want to take the lead on setting that up? @razetime @sudheesh001?

**Comment by enoch85** [comment]
Here is a script that I use to set up Let's Encrypt: https://github.com/enoch85/ownCloud-VM/blob/master/lets-encrypt/activate-ssl.sh

**Comment by simonv3** [comment]
Hey @enoch85 can you please clarify - does that script enable using let's encrypt for a GitHub hosted site?

**Comment by enoch85** [comment]
@simonv3 As I wrote, "(Adapted for ownCloud)", so - no, not a GitHub hosted site. But it could be a source of inspiration for making a script that does :)

**Comment by simonv3** [comment]
@enoch85 It's presumably meant to be run on the servers for which you're enabling SSL right? Or at least having access to them? If that's the case, I'm not sure GitHub grant us that access! If not, I'd love to hear how :)

**Comment by enoch85** [comment]
@simonv3 Aah, so this repo is about a Github hosted site? Never understood why I was added. I'm a member of the ownCloud design team, and I also host VMs on my site: [Tech and Me](https://www.techandme.se/pre-configured-owncloud-installaton/). 

The script I linked is a part of the installation where the user gets a real SSL cert via Let's Encrypt on his/her server.

Isn't SSL included on GitHub hosted sites? I'm surprised!

**Comment by simonv3** [comment]
You probably are just "watching" the repo automatically if you're a member of the opensourcedesign team.

> Isn't SSL included on GitHub hosted sites? I'm surprised!

You and me both! I actually haven't investigated this, and it's entirely possible that this is an option?

**Comment by enoch85** [comment]
@simonv3 Please update us if you find anything. :)

**Comment by sudheesh001** [comment]
I think Kloudsec is by far the best solution and we should go ahead with that. I'd love to help moving it to https:// but that'd need access to the domain credentials so that the DNS can be changed from github to kloudsec :smile:

**Comment by RichardLitt** [comment]
After researching it a bit, I am trying to use [netlify](https://www.netlify.com). Happy to let you know how this works out for me, and might be another alternative.

Progress on this issue seems to have stalled. Any updates? Are we waiting for consensus?

**Comment by simonv3** [comment]
Waiting for someone to take action I think!

**Comment by RichardLitt** [comment]
Ok. I have now switched to Netlify - this was a mostly painless experience, and I am happy with the result. I keep hosting on GitHub pages, but just changed the DNS records and enabled it on netlify. 

I wrote up a more comprehensive notes [here](https://github.com/RichardLitt/knowledge/blob/master/ssl-security.md). Happy to help whoever controls the DNS records for opensourcedesign with the transfer.

**Comment by simonv3** [comment]
I think that's @jancborchardt? Or maybe @bnvk?

**Comment by jancborchardt** [comment]
It’s me. :) The domain is registered at https://gandi.net and I could simply obtain an SSL certificate there I guess. That seems simpler than using yet another third party service.

**Comment by RichardLitt** [comment]
@jancborchardt That should work. :)

**Comment by RichardLitt** [comment]
@jancborchardt Can I help you obtain an SSL certificate?

**Comment by elioqoshi** [comment]
Let's expense that through Open Collective @jancborchardt

**Comment by RichardLitt** [comment]
Netlify is free. Might be easier to do?

**Comment by simonv3** [comment]
+1 for netlify. I wonder if we can build the site in the same way we do on GitHub (w/ nested repositories and such) on netlify as here.

**Comment by RichardLitt** [comment]
Hard to test for the submodules routing properly using the config, but it sure looks like it builds. 

Main: http://burser-mousedeer-10756.netlify.com/
Jobs page: http://treasurer-cruiser-16614.netlify.com/

I think it should work if you add in the URL to Netlify.

**Comment by RichardLitt** [comment]
I have https://58liters.com running the main site (as a test ground, using a domain I have but haven't been using). I will keep you updated about getting the jobs submodule working on this. Currently not sure how to do that.

**Comment by simonv3** [comment]
Thanks @RichardLitt!

**Comment by RichardLitt** [comment]
> Based on what you're doing, I'd recommend building each "sub" repo (like jobs) into a separate Netlify site, with a custom subdomain (like jobs.58liters.com), then set up a _redirects file in the main (opensourcedesign.github.io) repo that redirects /jobs/* links to the subdomain site. (Redirect docs: https://www.netlify.com/docs/redirects/)

Would that work for us?

**Comment by simonv3** [comment]
So that would mean we'd switch from using */jobs/* to jobs.opensourcedesign?

**Comment by RichardLitt** [comment]
Yes. I'm not sure what that would do to http://opensourcedesign.net/jobs/jobs/2017-02-28-sinonjs-homepage-design, either.

**Comment by m1guelpf** [comment]
@bnvk  I have been using CloudFlare for 3 years and never had any problem. I also usually login uing TOR, and I haven't had any problem disabling that captchas. Also, the other solution (kloudsec) is down and the owners don't answer why in ProductHunt, so it migth be dead.

**Comment by bnvk** [comment]
At this stage of game I don't think we need SSL urgently to bother w/
CloudFlare , etc... I'm exploring some things that might make sense for us
to move the whole site to a private server anyway, in which case we could
have real TLS, not the man-in-the-middled version like these services offer.

**Comment by sudheesh001** [comment]
@m1guelpf Yup, the last time I spoke to the kloudsec guys they took it down. It's kinda sad to see it go down.

**Comment by belenbarrospena** [comment]
I just got a friendly comment from the FOSDEM organisers about our website not supporting https. Any chance we could revive this issue? 

From the comments, people seems to be leaning towards netlify, although using Gandi might be even simpler. If there are any costs involved, there are funds available through the Open Collective donations. 

@jancborchardt Any chance you might have some time to look into this?  Happy to help, although I know nothing about these matters.

**Comment by comzeradd** [comment]
Since the website is based on a static content generator, it could be hosted for free on Gitlab pages and use Letsencrypt certificates. The downside of this is the need to update the certificates every 3 months.

There is a [detailed guide](https://about.gitlab.com/2016/04/11/tutorial-securing-your-gitlab-pages-with-tls-and-letsencrypt/) for this scenario.

**Comment by RichardLitt** [comment]
Again, Netlify also works very easily for https, and it is almost an automatic switch. Free of cost.

**Comment by m1guelpf** [comment]
My vote goes for Netlify. I have been hosting websites with them since I discovered them in this thread and I've never had any problems with them.

**Comment by simonv3** [comment]
The problem with Netlify, and likely Gitlab, is how we've set up the site into different components (jobs and events are in a different repo). 

The solution to that, and also massively simplifying our site, IMO (and this opinion has changed over time) is to bring everything into one repo. The thing we have to be most careful about here is making sure links still work.

**Comment by m1guelpf** [comment]
@simonv3 Another option would be to keep things in its own repository and use subdomains (like `jobs.opensourcedesign.net`)

**Comment by bnvk** [comment]
> Another (faster) option would be to keep things in its own repository and use subdomains (like jobs.opensourcedesign.net)

No @m1guelpf  this will not solve the issue as @simonv3 points out

> how we've set up the site into different components (jobs and events are in a different repo).

I have not read 100% of Netlify's docs, but I have not seen anything which makes it clear this multi-repo architecture is possible.

The fact the current site uses **multiple repos** is the biggest obstacle to adding TLS support. It's also why the topbar and footer are out of sync on the Jobs / Events page with the rest of the site. However, it's not that they need to **be in one repo** but rather how and where these repos are **when the site gets built** by Jekyll. Github Pages is limited in this respect as they treat each repo as a separate site. When you build the site yourself and adhere to the fact that all items sorted by time (articles, events, jobs) need to be int he `_posts/` folder like:

```
site
  - _includes/
  - _layouts/
  - _people/
  - _posts/articles/
  - _posts/events/
  - _posts/jobs/
  ...
```

This builds fine, while also keeping things in multiple repos. I did a bunch of work refactoring the sub-repos back after the Summit. This will be helpful regardless of merging things into one repo or keeping them separate. Technically, I think moving them into one repo is not the best strategy long term. 

To examine what I did, look at the `dev` branches for (this repo, jobs, and events). I also setup  webhooks which make the site deploy whenever a new commit appears on specified branch. It is only a small amount more of work to make this work for the main site. You can be preview this at [https://dev.opensourcedesign.net](https://dev.opensourcedesign.net). 

Note: that dev site is served via HTTPS, as it is trivial to setup using letsencrypt when self hosting the whole site.

I'm not dedicating any time to OSD at present, but if anyone wants access to my server and tips how to move the main site there, feel free to email me directly.

**Comment by jancborchardt** [comment]
I mailed Gandi.net (where we have the domain). They offer a 1-year free SSL cert for every domain (and 12 € a year afer) but it seems a bit confusing to set up. However when they answer and I figure it out I think this is the simplest way as we don’t have to maintain/use yet another provider or service.

**Comment by m1guelpf** [comment]
@jancborchardt Good news, Let's Encrypt offer SSL certificates for free! No one should have to pay to get a certificate, so they register them for free. You can check [Troy Hunt's article about the happy path to SSL](https://www.troyhunt.com/the-6-step-happy-path-to-https/) to know more.
Also, bad news, you can't setup a SSL certificate with GitHub Pages with a custom domain, you have to use another hosting that supports it.

**Comment by ei8fdb** [comment]
I'd give a +1 to using Gandi. I've used them for hosting and domain 
purchasing for 15+ years. They're a good bunch.

They also sponsor good people doing good things.

It'd also be easy to get set-up. If it helps, I can contact them to ask 
them for support on set-up?

**Comment by jancborchardt** [comment]
@ei8fdb since you are also a domain contact, it would be great if you can contact them. I mailed the support but they sent me this what seems more like boilerplate advice:

> There are two types of free certificates.
> 1- If your are using a Gandi Simple Hosting solution, you can have a free certificate SSL to secure the Vhost.
> From your Simple Hosting interface, in the "sites" management, you will be able to launch a certificate creation.
> This certs will remain free as long as you will use Gandi hosting.
>
> 2- If your domain is managed @Gandi, here you will have the certificate free the first year, for a standard one address domain.
> Just order the certificate, and your cart will be set to 0 automatically.

Cause that’s not what I’m experiencing, at least with the updated v5 Gandi interface.

**Comment by simonv3** [comment]
Look if you procrastinate long enough these things fix themselves https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by jancborchardt** [comment]
@simonv3 I thought we use A records? I adjusted them at Gandi just before and am waiting for the propagation.

Also renamed the repository to https://github.com/opensourcedesign/opensourcedesign.net while we are changing stuff to reflect the proper domain name.

**Comment by jancborchardt** [comment]
Scratch that – renamed it back because it resulted in the jobs and events not loading.

**Comment by jancborchardt** [comment]
Seems the A records worked now? :)

https://opensourcedesign.net is running and the default (through "Force HTTPS" in Github repo settings).

**Comment by elioqoshi** [comment]
Yay! Thanks @jancborchardt !

**Comment by elioqoshi** [comment]
Seems Jobs and Events preview is now broken on the landing page. Do we need to do any further tweaking?

**Comment by jancborchardt** [comment]
Works again, good catch and fix :) https://github.com/opensourcedesign/opensourcedesign.github.io/pull/173
