### ISSUE TITLE
Update social media accounts with our awesome new logo

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#32]
Because, our logo :grinning:

**Comment by simonv3** [comment]
:+1: I have no idea who runs any of these. @jancborchardt?

**Comment by razetime** [comment]
@bnvk Yes, our logo.

**Comment by razetime** [comment]
facebook has our new logo. Who operates the others?

**Comment by evalica** [comment]
Status: 
- [x] [Website](http://opensourcedesign.net/) —  [P#30](https://github.com/opensourcedesign/opensourcedesign.github.io/pull/30), [P#37](https://github.com/opensourcedesign/opensourcedesign.github.io/pull/37)
- [ ] [GitHub](https://github.com/opensourcedesign)
- [ ] [Twitter](https://twitter.com/opensrcdesign)
- [x] [Facebook](https://www.facebook.com/opensrcdesign/) — [I#27](https://github.com/opensourcedesign/opensourcedesign.github.io/issues/27)
- [x] [Medium](https://medium.com/open-source-design) — [I#17](https://github.com/opensourcedesign/organization/issues/17)
- [ ] Other?

**Comment by evalica** [comment]
Also we need to have a way to know which person has the ownership to a particular service or create groups were multiple people can do this types of changes. Otherwise we cannot say those services are community handled.

**Comment by razetime** [comment]
@bnvk? I guess we should go ahead and change the logo
![osd-logo](https://cloud.githubusercontent.com/assets/11015319/11323632/e23972b2-913c-11e5-99bc-b3f40e2b5468.png)
 on github.

**Comment by bnvk** [comment]
@razetime juts did it!

**Comment by simonv3** [comment]
Thanks @evalica for using the checklist methodology :+1:

**Comment by jancborchardt** [comment]
Updated the logo on Twitter: https://twitter.com/opensrcdesign

The logo posted above by @razetime wasn’t square, here’s the square version:
![opensourcedesign](https://cloud.githubusercontent.com/assets/925062/11337520/e7d26a2e-91ed-11e5-944d-313c2b655bab.png)
