### ISSUE TITLE
Bug when inputting GitHub handle (?)

### ISSUE THREAD

**Issue by jsonin** [opensourcedesign/opensourcedesign.github.io#321]
I just submitted a job... and I got this upon submitting, when I included a github handle: {"success":false,"data":["github_handle"],"rawError":{"_smErrorCode":"INVALID_FIELDS","data":["github_handle"]},"errorCode":"INVALID_FIELDS"}

When I deleted the github handle (on Eriol's suggestion), the form submitted correctly.

**Comment by Ian2020** [comment]
My best guess is that file `staticman.yml` in the jobs repo is missing `github_handle` from its allowedFields, it should be added. So it currently reads:

```yaml
   allowedFields: ["organization", "org_url", "compensation",
                   "paid_details", "title", "description", "deliverables",
                   "how_to_apply", "links", "tags", "status", "date_posted",
                  "layout", "rate", "role"]
```
But should be:

```yaml
   allowedFields: ["organization", "org_url", "compensation",
                   "paid_details", "title", "description", "deliverables",
                   "how_to_apply", "links", "tags", "status", "date_posted",
                  "layout", "rate", "role", "github_handle"]

```

I can submit this as a PR to jobs repo. Looks like this is hosted on Heroku though, who can deploy/update it? Or is it updated automatically from the repo?

**Comment by Erioldoesdesign** [comment]
@Ian2020 I think you've got much more chance of someone reviewing the PR if you submit to the jobs repo. Looks like a solid proposal to me and I think you'll get more help via a PR 😄

**Comment by Erioldoesdesign** [comment]
Pretty sure this is the same issue as this: https://github.com/opensourcedesign/opensourcedesign.github.io/issues/119

**Comment by Ian2020** [comment]
Thanks @Erioldoesdesign, PR submitted to jobs as suggested.

**Comment by Ian2020** [comment]
Looks like a recent job was submitted ok and included a GitHub handle: https://github.com/opensourcedesign/jobs/pull/661. As OP already resubmitted their failed job without a handle I think this can be closed.
