### ISSUE TITLE
Remove or update the link to the 'open design foundation'

### ISSUE THREAD

**Issue by Erioldoesdesign** [opensourcedesign/opensourcedesign.github.io#331]
At the bottom of the [goals page](https://opensourcedesign.net/goals/) we have a link to the [Open Design Foundation](http://opendesign.foundation/) which was operational but is now a link that goes to an unrelated site.

I did a quick search around and cannot find a replacement/updated URL so my suggestion is one of the following:

1. We remove this section:
![Screenshot 2021-06-17 at 11 50 55](https://user-images.githubusercontent.com/11681324/122382949-4d909e00-cf62-11eb-93d6-98c7acea9150.png)

2. Construct a statement that explains that the site has gone down but there is an archive of the site here on way back machine: http://web.archive.org/web/20210125021057/http://opendesign.foundation/

**Comment by samrath-sudesh-acharya** [comment]
Hey @Erioldoesdesign ,I would like to resolve this issue

**Comment by Erioldoesdesign** [comment]
There is also the github repo for the open design foundation here: https://github.com/DesignOpen/designopen.github.io

we could include this too in the text?

**Comment by paurav11** [comment]
Hi @Erioldoesdesign, I've resolved issue #331. Hope it is okay now and meets your requirements. 👍
