### ISSUE TITLE
update favicons

### ISSUE THREAD

**Issue by Arhell** [opensourcedesign/opensourcedesign.github.io#353]
https://realfavicongenerator.net/favicon_checker?protocol=https&site=opensourcedesign.net%2F#.YQBQTI4zaMo

**Comment by Erioldoesdesign** [comment]
Can you give this issue a better description of why it was opened and what it solves please? PR's won't be approved until we understand the issue clearly :)

**Comment by Arhell** [comment]
> Can you give this issue a better description of why it was opened and what it solves please? PR's won't be approved until we understand the issue clearly :)

Of course, this will add favicons for all platforms + browser themes on mobile devices (android for example).
When the site opens, the browser cover changes to the desired theme (color)
