### ISSUE TITLE
menu doesn't work

### ISSUE THREAD

**Issue by Arhell** [opensourcedesign/opensourcedesign.github.io#357]
https://opensourcedesign.net/jobs/
![02-08-2021 19-16-51](https://user-images.githubusercontent.com/26163841/127892570-77c8a401-2561-41f4-95f5-dc2734f28b6d.jpg)

**Comment by ZoranPandovski** [comment]
Hello @Arhell thanks for reporting. Did you mean it doesn't expand on click or there is some other issue?

**Comment by Arhell** [comment]
> Hello @Arhell thanks for reporting. Did you mean it doesn't expand on click or there is some other issue?

Yes, I found how to fix it so I'll do it soon PR.

**Comment by Arhell** [comment]
Fix https://github.com/opensourcedesign/jobs/pull/721
