### ISSUE TITLE
Missing plugin

### ISSUE THREAD

**Issue by GarthDB** [opensourcedesign/opensourcedesign.github.io#36]
It looks like the notes plugin page is requiring a js file that doesn't exist.

```
- ./_site/slideshows/free-and-usable/plugin/notes/notes.html
  *  internal script ../../plugin/markdown/marked.js does not exist (line 175)
```

**Comment by GarthDB** [comment]
This is the only thing that is causing tests to fail currently.

**Comment by razetime** [comment]
@GarthDB Really, the files are there, but there is a wrong reference to the file, I guess.
![screen shot 2015-11-22 at 12 47 02 pm](https://cloud.githubusercontent.com/assets/11015319/11322532/4d3ff4d0-9117-11e5-9d71-78fc17c4e5a2.png)

**Comment by GarthDB** [comment]
The notes file is there, that's where the reference to the missing file is, it's missing the marked.js file.



—

**Comment by razetime** [comment]
So, where did marked.js go?

> On Nov 22 2015, at 12:51 pm, Garth Braithwaite
&lt;notifications@github.com&gt; wrote:  
The notes file is there, that's where the reference to the missing file is,
it's missing the marked.js file.  
  
  
  
—  
Sent from Mailbox  
  
On Sun, Nov 22, 2015 at 12:18 AM, Raghu Ranganathan  
&lt;notifications@github.com&gt; wrote:  
  
&gt; @GarthDB Really, the files are there, but there is a wrong reference to
the file, I guess.  
&gt; ![screen shot 2015-11-22 at 12 47 02 pm](https://cloud.githubusercontent.
com/assets/11015319/11322532/4d3ff4d0-9117-11e5-9d71-78fc17c4e5a2.png)  
&gt; \---  
&gt; Reply to this email directly or view it on GitHub:  
&gt; https://github.com/opensourcedesign/opensourcedesign.github.io/issues/36#
issuecomment-158734348

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/opensou
rcedesign/opensourcedesign.github.io/issues/36#issuecomment-158734688).![](htt
ps://github.com/notifications/beacon/AKgUl3wNq4XG_F1F5lAr_9NxfibcBcbNks5pIWRig
aJpZM4GnD5H.gif)

**Comment by GarthDB** [comment]
No idea, that's why I filed the issue instead of making a pull request with the fix. I don't know the story here and was hoping someone else did.
If it was deleted by accident let's get it back, or else we should delete `notes.html`

**Comment by duythien** [comment]
You can take look at https://github.com/opensourcedesign/opensourcedesign.github.io/tree/master/slideshows/free-and-usable#full-setup or just copy the folder markdown at https://github.com/hakimel/reveal.js/tree/master/plugin and done

**Comment by simonv3** [comment]
I think the notes here are just a remnant of pulling the non-compiled reveal.js files into the repo, something that *should* probably have been avoided.

@jancborchardt looks like you originally committed this, can you confirm?

Removing `notes.html` from the directory doesn't break the actual slideshow, so we can just remove it.
