### ISSUE TITLE
broken links in COC

### ISSUE THREAD

**Issue by Bhupesh-V** [opensourcedesign/opensourcedesign.github.io#383]
hey, 
just to inform the link https://adainitiative.org/2014/02/howto-design-a-code-of-conduct-for-your-community/ no longer exists or has moved somewhere else

Update seems like hoodie link is also not available anymore: http://hood.ie/code-of-conduct/

**Comment by jdittrich** [comment]
Thanks! 
We probably should do a bit of research on newer texts. 
@contributors  Meanwhile we could link to

* Ada initiative: https://web.archive.org/web/20150701085442/https://adainitiative.org/2014/02/howto-design-a-code-of-conduct-for-your-community/
* Hoodie: https://web.archive.org/web/20200827104710/http://hood.ie/code-of-conduct/
