### ISSUE TITLE
Written guidance on how to make a job on OSD successful

### ISSUE THREAD

**Issue by Erioldoesdesign** [opensourcedesign/opensourcedesign.github.io#393]
We don't have guidance docs about how a job poster can make their job successful.

Let's start a thread here on how to write an article - which could then be used in comms related to posting a job about how to make the post successful.

Ideas:
- Add a hello and contact info to your forum post when a job is approved
- Check the forum post at least once per month/when able to
- Answer questions for the designers, typical questions include etc....

**Comment by Dibyajyoti2002** [comment]
Hi , I was thinking about working on this issue , but before doing that , I just wanted to clarify something . Should the person working on this issue provide a documented approach and some tips on how to make a job post successful?

**Comment by jdittrich** [comment]
> …working on this issue provide a documented approach and some tips on how to make a job post successful?

Yes!

@Erioldoesdesign mentioned a few best practices, and I think it would also be good to provide a faux job example and why it is good. (Clear task, goals for the task, target group defined, contact person clear…)

Maybe start on an etherpad or gdoc or the like, in case you want to get quick feedback?

**Comment by Erioldoesdesign** [comment]
> Hi , I was thinking about working on this issue , but before doing that , I just wanted to clarify something . Should the person working on this issue provide a documented approach and some tips on how to make a job post successful?

Agreed with @jdittrich sounds like a perfect way to start a doc with some mock examples and the rest of the OSD community can help out by reviewing :)

**Comment by subz3r0o0** [comment]
hi, if this issue is still open i would love to contribute

**Comment by Erioldoesdesign** [comment]
> hi, if this issue is still open i would love to contribute

Go for it this is a open issue that will serve as the basis for a document that can be openly collaborated on

**Comment by subz3r0o0** [comment]
is this along the lines of what youre looking for? https://docs.google.com/document/d/1TvMIyV4AMG2y5y7Yy9WvdrgxEUEuA7366FZzaWIpz0c/edit?usp=sharing - and could i make any pull requests to push this into any repos?

**Comment by subz3r0o0** [comment]
is this ok, i sent an email also
:))

**Comment by Erioldoesdesign** [comment]
@subz3r0o0 can you give me access to your google document please - I sent a request for access via my email accounts or you can open up the document for public viewing so I can take a read and make any suggestion :)

**Comment by subz3r0o0** [comment]
Hi, I changed the access rights - is it ok now? 
Thanks

**Comment by subz3r0o0** [comment]
After finalising the writing, I plan to move it to a Canva document for aesthetic purposes :)

**Comment by Erioldoesdesign** [comment]
@subz3r0o0 Amazing work - i'm blown away at how detailed and thoughtful your work on this issue is 👏 🚀 

I've added some extra examples and edited some words - feel free to accept or reject those in the google document as you see fit :) (I will not be upset if you don't like my writing 😄 )

I would recommend this be added both as a .md file in the jobs repository and also an article on the website: https://opensourcedesign.net/articles/

I would also think it would be great to add as a forum post. If you want to make a visually exciting version in Canva do go ahead and we can upload the open doc files or .pdf to the repo for people to see but also embed in the article page :)))))))

**Comment by subz3r0o0** [comment]
I made this on Canva, what do you think? :))
https://www.canva.com/design/DAGEZuwNXPM/ApoXbQOLvP_ep6veR7fulw/edit?utm_content=DAGEZuwNXPM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by Erioldoesdesign** [comment]
> I made this on Canva, what do you think? :)) https://www.canva.com/design/DAGEZuwNXPM/ApoXbQOLvP_ep6veR7fulw/edit?utm_content=DAGEZuwNXPM&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

Love it! looks great @subz3r0o0 
So What i'd suggest next in order to contribute this to the website + wider community is:

1. Make a Pull Request in the ['_posts' section of this repo](https://github.com/opensourcedesign/opensourcedesign.github.io/tree/master/_posts) (there's a [how to add an article in that directory](https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/_posts/How-to-add-an-article-to-open-source-design.md) - that's the folder that populates the [Articles](https://opensourcedesign.net/articles/) section of the website. I would recommend just copy pasting the text into a page and adding formatting if you can.
2. Make a Pull Request for a .pdf (or other open format document) from your Canva file in the top level directory of the [jobs repo](https://github.com/opensourcedesign/jobs) it would also be good to have as a .md (markdown) file there too just in case people going to the repo are wary of .pdf files (e.g. .pdf files can have malware in them :) ) You can then link this file in the article and we can also do a addition to the jobs page to link to this guide.
3. Lastly, it'd be great if you can show this document on the forum: https://discourse.opensourcedesign.net/ we have a [related thread here](https://discourse.opensourcedesign.net/t/can-we-collaborate-on-a-discourse-thread-or-article-about-how-to-write-a-job-posting-that-gets-results/2599/7) and I'm sure lots of community members will be excited!

**Comment by subz3r0o0** [comment]
Done! I made a pull request.

**Comment by Erioldoesdesign** [comment]
Closing this issue as it was done 😄 https://github.com/opensourcedesign/opensourcedesign.github.io/pull/445/files
