### ISSUE TITLE
Move to using git submodules

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#40]
Given the architecture of the OSD website and it's use of multiple repos (which I am partly to blame for), it might be fortuitous to move towards making many of the repos (jobs, events, organization, slideshows, etc...) submodules. This is the pattern we use at [Qubes OS](https://qubes-os.org) and can be seen via the [`.gitmodules` files](https://github.com/QubesOS/qubesos.github.io/blob/master/.gitmodules).

I think this would make developing a bit more easy!

**Comment by GarthDB** [comment]
I hate submodules. I have been traumatized.



—

**Comment by bnvk** [comment]
@GarthDB that's unfortunate. I'm sorry for your trauma. I've had 2/3 good experiences, but that 1 time...

**Comment by GarthDB** [comment]
This one sums it up: https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/




—

**Comment by jancborchardt** [comment]
We also use a submodule for 3rdparty libraries in ownCloud. Works quite well and it’s a good fit for our site architecture I think.

Btw @GarthDB you might want to get rid of that »Sent from Mailbox« signature. ;)

**Comment by simonv3** [comment]
Is it possible to set this up without confusing non-terminal habitants?

Is there a way we could test this before committing to it?

**Comment by GarthDB** [comment]
Nope, I love sending stuff from mailbox.




Why not do a single repo jekyll blog with multiple categories for posts. It would let you share stylesheets and assets easier, and would avoid the submodule complexity.


—

**Comment by bnvk** [comment]
> Is it possible to set this up without confusing non-terminal habitants?

Do you mean "do the various GUI Git clients support sub modules?" I don't know, I haven't used a GUI Git app in years.

> So if submodules are such a pain, what are the alternatives?

I'm hesitant to agree with the alternatives that articles suggests- an unmaintained since 2012 repo, a bad URL...

The nice thing about Git submodules is **you don't to use it** you can just manually clone all the things yourself in their right place.

> Why not do a single repo jekyll blog with multiple categories for posts

@GarthDB my reasoning for segmenting things out: 

- **Allows for different dependencies / approaches** - such as `slideshows` which is different layout and different front-end dependencies `reveal.js` which the rest of the site doesn't depend on
- **Keeps the repos small over time** - so we don't end up with a repo sized 300+ MB, such that if a person wants to add a `job` or `event` they don't have to clone a gargantuan repo to participate
- **Makes "subscribing" more simple & granular** - for conversation / watching / participating purposes
- **Github as a mailing list** - basically using the OSD repos as a mailing list with different categories ppl can subscribe to (jobs, events, or helping with the site)

I don't think simply using Jekyll categories would achieve this. But you're right, it would make front-end assets slight more normal and easy. However, this is why I'm suggesting `git submodules` as my experiences with Qubes site and them has been great in this respect.

> Nope, I love sending stuff from mailbox.

I don't think @jancborchardt was saying to stop using Mailbox, but rather configure it so that people reading this don't have to read your signature in every comment, as Mailbox doesn't respect the proper `-- ` spec. to dilleneate signatures.

**Comment by GarthDB** [comment]
The last reasons make sense, but Jekyll with separate categories could easily do different layouts, or no layouts at all. In fact you can default to a certain layout based on a the directory it is in.

Also using GitHub as a mailing list isn't always ideal; the signal to noise ratio can get rough as we get off topic. It would probably be best to add feeds to things people can subscribe to if they are interested.

**Comment by jancborchardt** [comment]
Regarding the current architecture of the site, git submodules would just be an upgrade/simplification of the process. Whereas you now have to clone everything manually (as you could still do, like Brennan mentioned above), it would change to one command. So it's not really that big of a change, simply an adjustment.

**Comment by thinkxl** [comment]
IMO, it may be simplification for developers, but all the opposite for designers (that are not experienced in git, GitHub, CLI, etc.)

**Comment by bnvk** [comment]
I ultimately decided against using submodules (due to needing to run update scripts on a webhook in order to trigger updates). As per making it easier to develop & keep up-to-date, these lil [bash scripts](https://github.com/opensourcedesign/opensourcedesign.github.io/tree/master/scripts) do a nice job of making it easier!
