### ISSUE TITLE
Website restructuring: Merge "Projects" with "Resources"

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/opensourcedesign.github.io#415]
**Problem:** A primary link in our navigation is "Projects". It is pluasible to assume these are projects that are primarily run by OpenSourceDesign, but these are projects that we think have a good UX practice or are otherwise. While this is an helpful information, it might be not ideal to have it as a main navigation link. 

**Suggestion:** Merge "Projects" with "Resources".

**Comment by mjubair** [comment]
Hi @jdittrich, I have added a PR for this issue. Please review and let me know if this meets your requirements. Thanks

**Comment by Erioldoesdesign** [comment]
@mjubair reviewing now :)
