### ISSUE TITLE
Unclear installation instructions in README

### ISSUE THREAD

**Issue by randmon** [opensourcedesign/opensourcedesign.github.io#419]
https://github.com/opensourcedesign/opensourcedesign.github.io/blob/3115e7d9675caed91171cf905cf09050dd14516c/README.md?plain=1#L38

**Comment by babybeans** [comment]
Hello, a colleague and I would like to work on this issue as a school project. Is anyone working on it currently?

**Comment by subz3r0o0** [comment]
hi! hope you are well. can i be assigned to this issue if its still available? thanks. i am going to complete all of them soon

**Comment by Erioldoesdesign** [comment]
> hi! hope you are well. can i be assigned to this issue if its still available? thanks. i am going to complete all of them soon

Done 👍 I look forward to your contribution.

You e made Fantastic contributions lately. If you'd like some Open Source Design items like a t-shirt sent to you in mail then please drop me an email @ erioldoesdesign@gmail.com 😄

**Comment by subz3r0o0** [comment]
i made a pull request with a few slight tweaks for better clarity in the readme, let me know what you think :)

**Comment by Erioldoesdesign** [comment]
https://github.com/opensourcedesign/opensourcedesign.github.io/pull/448 < once merged this issue should close
