### ISSUE TITLE
Open Collective Button Hover Issue

### ISSUE THREAD

**Issue by AkshayRaj1999** [opensourcedesign/opensourcedesign.github.io#429]
![Screenshot_10](https://github.com/opensourcedesign/opensourcedesign.github.io/assets/106061432/f66321c6-ae5f-4927-bdee-623468bde560)
![Screenshot_9](https://github.com/opensourcedesign/opensourcedesign.github.io/assets/106061432/5dbaa4e9-851b-475c-befd-48eb0cd29148)
when hovering other buttons the correspondent logo has pure white fill but when it comes to open-source its bit different. 
(assets attached ⬇️)
![opencollective-icon (1)](https://github.com/opensourcedesign/opensourcedesign.github.io/assets/106061432/d3cd5142-8f8f-403a-aaac-f50f78582af8)

**Comment by Erioldoesdesign** [comment]
Looks like the Open Collective logo uses an .svg file imported in as the button icon (which is different to the other icons on the buttons which I think, pull in from an icon library) either way, it also looks like the CSS for the open collective button is slightly different to the other buttons e.g. no ':before' CSS selector.

I imagine it's a reasonably quick fix for folks with the Front end/.svg knowledge
![Screenshot 2024-04-02 at 11 50 17](https://github.com/opensourcedesign/opensourcedesign.github.io/assets/11681324/58c29005-9770-47ea-81c3-919fda09ff2d)

**Comment by subz3r0o0** [comment]
I created a pull request - [(https://github.com/opensourcedesign/opensourcedesign.github.io/pull/441)]
Let me know if you can have a look.

**Comment by Erioldoesdesign** [comment]
https://github.com/opensourcedesign/opensourcedesign.github.io/pull/441

**Comment by Erioldoesdesign** [comment]
Closing as the fix was merged! https://github.com/opensourcedesign/opensourcedesign.github.io/pull/441
