### ISSUE TITLE
Please make a mastodon account for open source design

### ISSUE THREAD

**Issue by slrgt** [opensourcedesign/opensourcedesign.github.io#442]
Would love to be able to follow and share posts from Open Source Design on mastodon and other activitypub software. It would be very fitting for the Open Source Design community as well considering its all open source and soo many people using mastodon etc love open source software and design

Thanks for the amazing work y'all do!

**Comment by jdittrich** [comment]
We have an account at: https://mastodon.social/@opensourcedesign

**Comment by jdittrich** [comment]
We have an account at: https://mastodon.social/@opensourcedesign

**Comment by slrgt** [comment]
Oh thanks i couldnt find it on your website or anything so i didnt know

**Comment by jdittrich** [comment]
>  i couldnt find it on your website

That sounds like a (different) bug! Do you want to create an issue?

**Comment by slrgt** [comment]
> >  i couldnt find it on your website
> 
> 
> 
> That sounds like a (different) bug! Do you want to create an issue?

Done :)
