### ISSUE TITLE
Mastodon account isnt listed on website

### ISSUE THREAD

**Issue by slrgt** [opensourcedesign/opensourcedesign.github.io#443]
The mastodon account isn't listed on the website, open collective, or the forum

**Comment by Erioldoesdesign** [comment]
@slrgt I believe we made our Mastodon account recently - possibly last year or maybe 2022. If you'd like to submit a PR adding the logo + [link](https://hachyderm.io/@opensourcedesign@mastodon.social) to the pages you think it should be on we'd very much welcome that contribution :)

**Comment by subz3r0o0** [comment]
Hi everyone! Could I be assigned to this and add it to the main page - for instance, as a button on the Contact Us page and as a footer :)

**Comment by Erioldoesdesign** [comment]
Added them here in the forum: https://discourse.opensourcedesign.net/t/open-source-designs-social-media-links/3902

working on fixing the website etc. now

**Comment by Erioldoesdesign** [comment]
Added to our github profile https://github.com/opensourcedesign

**Comment by Erioldoesdesign** [comment]
Added to Open Collective

**Comment by Erioldoesdesign** [comment]
https://github.com/opensourcedesign/opensourcedesign.github.io/pull/455

**Comment by Erioldoesdesign** [comment]
https://github.com/opensourcedesign/opensourcedesign.github.io/pull/456

**Comment by Erioldoesdesign** [comment]
Tested the links on the **website** - they work!

Tested the links on the **forum** - they work!

Tested the link on the **Open Collective** - It works!
