### ISSUE TITLE
Fix titles on sub pages (articles, events)

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#45]
Title just shows Open Source Design. It should probably show the name of the article or event being viewed as well.

**Comment by jancborchardt** [comment]
Yup separated by an en dash:

> Article title – Open Source Design

**Comment by bnvk** [comment]
This is still an issue, it seems like it should be addressed in #49 but I don't think it is @balyasnikovk wanna take a stab at this in your pull req as well since it's very similar part of the site's code?

**Comment by grahamperrin** [comment]
If not automated, then can some titles be set manually? 

I should recommend beginning with: 
- the four top-level items
- [Open source design needs better collaboration tools – Open Source Design](http://opensourcedesign.net/open-source/communities/collaboration/tools/design/2017/03/27/osd-needs-better-collaboration-tools.html)

**Comment by Jc-L** [comment]
Issue is solved for articles, jobs, and first-level heders. Not working for events but these are not directly managed by jekyll, from what I see.
Should this issue be closed ?

**Comment by Erioldoesdesign** [comment]
I think this can be closed :)
