### ISSUE TITLE
Chat room link doesn't seem to be working

### ISSUE THREAD

**Issue by asmitbm** [opensourcedesign/opensourcedesign.github.io#461]
I was looking into how I could contribute to the Open Source Design community and found this link: https://chat.opensourcedesign.net/. Unfortunately, the link no longer works. Do you know of an alternative?

**Comment by jancborchardt** [comment]
@asmitbm yes, we don’t really use that channel anymore. Our main platform is Discourse at https://discourse.opensourcedesign.net/
If you like, you can submit a pull request to remove the outdated links where they appear. :)

**Comment by asmitbm** [comment]
@jancborchardt  Sure, I'd be happy to create a PR. I also found some other broken links but don't have alternative sources for them. In the paragraph under "How are you different from Open Design":

> There is a community called [Open Design](https://opendesign.foundation/) that sometimes gets confused as us. From [this conversation](https://github.com/opensourcedesign/resources/issues/14) our differences are:

Both links seem to be dead. Should I remove this line?

**Comment by jancborchardt** [comment]
@asmitbm sure, sounds good!
