### ISSUE TITLE
Lack of Padding on job pages

### ISSUE THREAD

**Issue by razetime** [opensourcedesign/opensourcedesign.github.io#47]
![screen shot 2015-12-03 at 3 14 39 pm](https://cloud.githubusercontent.com/assets/11015319/11626035/83b4b2f4-9d05-11e5-91f4-a51adc597e9e.png)
The padding and margins on our articles is well, absent, and I think we need to fix that up.

**Comment by jancborchardt** [comment]
cc @simonv3 any idea?

**Comment by simonv3** [comment]
Yep, the changes that were made in events and the normal site still need to be pulled in to the jobs pages site. This is a reason for #40.

If I get a chance today I can do it, it should be really quick.
