### ISSUE TITLE
Add font-awesome to front-end deps

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#5]
https://fortawesome.github.io/Font-Awesome/icons/ because, icons :grin:

**Comment by simonv3** [comment]
:+1: would close issue on checklist as well I suspect: https://github.com/opensourcedesign/foss-contributors-checklist/issues/4.

**Comment by jancborchardt** [comment]
Yeh, even though not all of the icons are awesome it’s probably easiest. :) And it showcases a great open source design project.

**Comment by Xaviju** [comment]
Why not using SVGs instead of iconfonts? 
https://css-tricks.com/icon-fonts-vs-svg/

We could use CC icons from nounproject https://thenounproject.com/

**Comment by jancborchardt** [comment]
I must say I also prefer SVG. The only advantages are:
* really quick coloring – but we won’t really use color
* only one file is loaded – which we can fix using https://github.com/jkphl/iconizr

On top of that the style & quality of icons available on thenounproject is better. And I mean, how many do we need?

**Comment by jdittrich** [comment]
Sorry, but – what are the icons meant to be used for?

**Comment by simonv3** [comment]
How much of a hassle is using SVGs versus including a link to font awesome's CDN? And updating the SVG file every time we add another one? (I'm hesitant to add another build step to this project that's meant to be accessible and easily maintainable).

Also @jdittrich raises a good point. For the foss-contributors-checklist it's purely aesthetic, and that particular project might be better served by using nounproject SVGs. But as something to use across all of our sites that follows a standardized theme?

**Comment by RichardLitt** [comment]
I believe this can be closed. We're using FA on the site, currently. Reopen if I am mistaken.
