### ISSUE TITLE
Add link to "Join our Group on GitHub" issue in organization

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/opensourcedesign.github.io#50]
Link is here: https://github.com/opensourcedesign/organization/issues/29

**Comment by Shruti9520** [comment]
@simonv3 Where do we need to add this link?

**Comment by simonv3** [comment]
How about right underneath "read more about our goals".

@Shruti9520 do you think there's a good place for it that I might be missing?

**Comment by Shruti9520** [comment]
@simonv3 That would be great.
 Can I fix it?

**Comment by simonv3** [comment]
@Shruti9520 Please do!

**Comment by Shruti9520** [comment]
@simonv3 The two paragraphs above it is also not aligned properly. Can I fix them too?

**Comment by simonv3** [comment]
@Shruti9520 no need to ask for my permission if you see something broken :)

**Comment by simonv3** [comment]
Or for anything really.

**Comment by Shruti9520** [comment]
@simonv3 PR#75

**Comment by Shruti9520** [comment]
@simonv3 Here is the screenshot--( aligned paragraph and added link)
![open1](https://cloud.githubusercontent.com/assets/20228417/22517170/4a1609ce-e8ce-11e6-8918-d3932e88e5f0.png)

**Comment by Shruti9520** [comment]
@simonv3 Here is the screenshot--(updated footer)
![open2](https://cloud.githubusercontent.com/assets/20228417/22517205/65542ec8-e8ce-11e6-937e-208403f59c5a.png)

**Comment by simonv3** [comment]
@Shruti9520 looks great! Can you capitalize GitHub so that it's in line with their brand? The H is a capital.

**Comment by Shruti9520** [comment]
@simonv3 Sure :)

**Comment by Shruti9520** [comment]
@simonv3  PR#76

**Comment by simonv3** [comment]
Awesome. Merged!

**Comment by bnvk** [comment]
Seems fixed. Closing.
