### ISSUE TITLE
Event list and job list not appear in homepage- Firefox43 and Chrome48 runs on OSX 10.11.1

### ISSUE THREAD

**Issue by digitigrafo** [opensourcedesign/opensourcedesign.github.io#51]
![schermata 2016-01-25 alle 11 15 41](https://cloud.githubusercontent.com/assets/11573104/12548202/0c09804c-c355-11e5-8df1-a7e500d1ac26.png)
Also in Chrome 48, the same thing.

**Comment by simonv3** [comment]
They don't appear anywhere, they're not really implemented properly yet...

Happy to accept PRs fixing this though!

**Comment by jancborchardt** [comment]
Yup, same here, was contacted on IRC already by a person who noted there are no future events.

We did show them in the past though, no? How was it broken and how can we fix it? cc @gillisig @bnvk

**Comment by jancborchardt** [comment]
If it’s more work then we should put a link to the Events / Jobs pages at least. Or is it a quick fix?

**Comment by bnvk** [comment]
> We did show them in the past though, no? How was it broken and how can we fix it? cc @gillisig @bnvk

I think there is a few ways to go about this- one would be with JS + ajax calls, the other would be using Jekyll and pull in the sub-repo data!

> If it’s more work then we should put a link to the Events / Jobs pages at least. Or is it a quick fix?

There are links at the top of the page. But adding a button to the bottom like "See all events" makes sense!

**Comment by simonv3** [comment]
It really shouldn't be too much work, and we never had an "events" or a "jobs" feed on the front page. 

I half-assed implemented something but just hadn't had time to look at it again.

**Comment by dominicrico** [comment]
Fixed with #52
Filled in six events and jobs instead of the whole list, because they could be really long over time. Maybe a pagination or something else would be nice.

**Comment by simonv3** [comment]
This is great. Thanks @dominicrico. 

Live on the site now :) [opensourcedesign.net](http://opensourcedesign.net)

**Comment by dominicrico** [comment]
Glad to see it live that quick! Will do more soon!

**Comment by bnvk** [comment]
@dominicrico awesomely done! Thanks so much for contributing :+1:
