### ISSUE TITLE
Breaking formatting on about and code-of-conduct pages

### ISSUE THREAD

**Issue by sudheesh001** [opensourcedesign/opensourcedesign.github.io#59]
It currently looks like this and doesn't follow the overall theme the website uses.
<img width="1440" alt="screen shot 2016-04-08 at 10 01 04 am" src="https://cloud.githubusercontent.com/assets/4545925/14374244/45e8aea4-fd71-11e5-9da1-0ce527cb723a.png">
<img width="1440" alt="screen shot 2016-04-08 at 10 00 53 am" src="https://cloud.githubusercontent.com/assets/4545925/14374249/512f84e0-fd71-11e5-831c-6ccf6b1dd849.png">

It should instead look like this, just like a regular post.

<img width="1440" alt="screen shot 2016-04-08 at 10 03 33 am" src="https://cloud.githubusercontent.com/assets/4545925/14374251/5d53cb00-fd71-11e5-822d-31eab1d838c9.png">

Required class change is : `post col-md-8 col-md-offset-2`
Fix: `layout: page` => `layout: post`

**Comment by daminisatya** [comment]
#60
