### ISSUE TITLE
Have a link to the actual website in Open Source jobs

### ISSUE THREAD

**Issue by raghunayyar** [opensourcedesign/opensourcedesign.github.io#61]
Currently, the title refreshes to the same page. There should be a link to the open source project which is posting a job. @opensourcedesign/people

**Comment by equinusocio** [comment]
> the title refreshes to the same page
What title do you mean?

**Comment by equinusocio** [comment]
When publishers post a new job, the file must contain `org_url: http://...` inside the `front_matter`. 
If not present, it creates an anchor

**Comment by RichardLitt** [comment]
I believe this can be closed. @raghunayyar can you replicate?

**Comment by simonv3** [comment]
Yeah this was fixed a while ago.
