### ISSUE TITLE
Merge foss-contributors-checklist repo into this one

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#62]
So... I was a bit too "repo happy" early on, thus I think merging things where appropriate would be a good idea at this stage of our growth.

I opened [an issue in Organization](/opensourcedesign/organization/issues/42) about combing appropriate repos into that one, which I believe should stay separate for now!

However, upon reviewing, I think the following can (and should be) merged to this repo

- [foss-contributors-checklist](/opensourcedesign/foss-contributors-checklist)

**Comment by simonv3** [comment]
👍 . yes because it's a website.

**Comment by Erioldoesdesign** [comment]
I think this can be closed in favour of the repo merging epic:https://github.com/opensourcedesign/opensourcedesign.github.io/issues/334
