### ISSUE TITLE
Making more clear how to contribute

### ISSUE THREAD

**Issue by LibreAnne** [opensourcedesign/opensourcedesign.github.io#66]
Hi open source design. I am new to your community. I want to help in small ways but an unsure of best way. I looked at the contributing file but seems not yet done. I know got and github a little but dont know how you suggest developing your site with all the different repos

**Comment by simonv3** [comment]
Yes! We definitely are looking at fixing that @LibreAnne. What kind of contributions would you like to make?

**Comment by bnvk** [comment]
Ah. That is a file I started creating and did not finish, apologies :stuck_out_tongue_closed_eyes:  I started writing these [command line scripts](https://github.com/opensourcedesign/opensourcedesign.github.io/tree/master/scripts) to make it easier to clone / update the only repos used for the public website. However, those scripts do take into account a user needing (or having already) forked all the repos to their own Github account, which is one of the steps needed for developing the website as I suggest we recommend to new users like @LibreAnne for instance.

**Comment by evalica** [comment]
Hi @LibreAnne . There are various ways to contribute, depends on what you want to do. You can:
- make PRs for the website or other repos, 
- you can give feedback to the various issues we have open, 
- you can try to design something from our job board, 
- you can just come and chat on IRC, 
- you can help us define what this new contributors list should contain :)
- etc.
We are still trying to figure things out ourselves.

**Comment by evalica** [comment]
I think this is covered by http://opensourcedesign.net/contribute/. WDYT @simonv3 ?

**Comment by simonv3** [comment]
Yep, I think so! Though that page can be fleshed out. 

A link to that is now also on the front page http://opensourcedesign.net/

**Comment by Erioldoesdesign** [comment]
I think this is important to note that a contributor didn't know how to get involved but a lot has changed since 2016/2017 so I'm closing :)
