### ISSUE TITLE
Resources link or page broken

### ISSUE THREAD

**Issue by RichardLitt** [opensourcedesign/opensourcedesign.github.io#67]
The README for opensourcedesign/resources points to http://opensourcedesign.net/resources/, which is broken. Where should it point?

**Comment by simonv3** [comment]
Fixed, though the website looks like shit.

**Comment by RichardLitt** [comment]
I'm not sure it's fixed. The link points to the same place, but now I see a webpage with a circular link:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>resources</title>
    <link href="http://opensourcedesign.net/resources/assets/css/style.css?v=6c0d0874f91033e2ce40789a138834ff357ec768" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <h1 id="resources">Resources</h1>

<p>View the Open Source Design list of<br />
<a href="http://opensourcedesign.net/resources/">Resources</a></p>

<p>Please send a pull-request to contribute to this list :smile:</p>

    </div>
  </body>
</html>
```

I'd help, but I'm not sure where it should point or how your system works.

**Comment by simonv3** [comment]
It's a GitHub pages site based on this repo. It's just showing the README.md page: https://github.com/opensourcedesign/resources/blob/master/README.md

**Comment by RichardLitt** [comment]
Shouldn't resources show the Resources page? 

Maybe we could move the resources page contents to the README?

**Comment by simonv3** [comment]
I just kind of assumed it would show index.md first, but I guess not! If there's no way to redirect GitHub pages to show index.md or resources.md as the main page than yeah, why don't we copy the readme.md over. Is that something you want to do @RichardLitt?

**Comment by simonv3** [comment]
Awesome! Thanks for doing that. That content now made it across to /resources/. I reckon we'll have to do some proper jekyll magic (copying styles and the static site) to make it fit the style guide, but that can be a different issue.

I just realized that I have spent hours in the past looking for this information across the repos and couldn't find it. Thanks for bringing this together @RichardLitt
