### ISSUE TITLE
Error on submitting jobs

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#71]
This was reported on IRC by @Xaviju who experienced an issue upon using the [nice submission form](http://opensourcedesign.net/opensrcdesignjobs/)

```
[{"code":"INVALID_FIELDS","data":["org_url","rate"]}]
```

**Comment by pdurbin** [comment]
Yes, he mentioned the trouble at https://botbot.me/freenode/opensourcedesign/msg/79358252/

I believe the code for the form is in this repo: https://github.com/opensourcedesign/opensrcdesignjobs

**Comment by simonv3** [comment]
Didn't mean to close this via that commit, but can someone test?

**Comment by george2seven** [comment]
Hello, I am having the same issue with a somewhat different error message returned:

[{"code":"INVALID_FIELDS","data":["rate"]}]

Thanks

**Comment by simonv3** [comment]
@george2seven. Thanks for reporting it! Can you try now?

**Comment by george2seven** [comment]
@simonv3 Fixed. Thanks!
