### ISSUE TITLE
Move "opensrcdesignjobs" form into Site or Jobs repo

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#72]
For (code) organizational purposes, we should move the code in [this repo](/opensourcedesign/opensrcdesignjobs) into either this repo or the [jobs](/opensourcedesign/jobs) repo.

**Comment by simonv3** [comment]
Yep! Should be fairly easy to do. You'd just have to move the index.html here and call it jobs-form.html or something. The staticman.yml file in that repo is actually redundant. The one in this repo gets used.

**Comment by simonv3** [comment]
This is done by the way, that repo can be closed.
