### ISSUE TITLE
Add Open Collective donors & call to donate to website (and maybe Github)

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/opensourcedesign.github.io#73]
We could have a nice list of the supporters on the frontpage by using this website banner:
https://github.com/OpenCollective/OpenCollective/wiki/Website-banner

Similarly also with the Github banner, but not sure which repo we should add it to (I guess /organization?)
https://github.com/OpenCollective/OpenCollective/wiki/Github-banner

**Comment by yashrajjain726** [comment]
give me a list of supporters and I will add it.

**Comment by jancborchardt** [comment]
This has actually already been done some time ago, see:
- "Supporters" section at https://opensourcedesign.net/
- In the readme of this repository as well :) https://github.com/opensourcedesign/opensourcedesign.github.io/#-contributors-backers--sponsors
