### ISSUE TITLE
Issue regarding footer

### ISSUE THREAD

**Issue by Shruti9520** [opensourcedesign/opensourcedesign.github.io#74]
The font-size of "Chat With Us" and "Code of Conduct" doesn't match with "opensourcedesign" and "opensrcdesign" in the footer.
Also, the icon is not displayed along with "Chat With Us" and "Code of Conduct".

**Comment by RichardLitt** [comment]
> The font-size of "Chat With Us" and "Code of Conduct" doesn't match with "opensourcedesign" and "opensrcdesign" in the footer.

If you inspect, they are the same size - what looks different is that the first two don't have any capital letters, and only one ascender (the `d`). The same CSS applies to both, I believe. 

> Also, the icon is not displayed along with "Chat With Us" and "Code of Conduct".

<img width="657" alt="screen shot 2017-03-08 at 9 19 32 am" src="https://cloud.githubusercontent.com/assets/910753/23707436/5bf64546-03e0-11e7-86a7-3e1c34ea75a6.png">

I am not able to replicate. What do you mean?

**Comment by Shruti9520** [comment]
@RichardLitt This is already solved in this PR- https://github.com/opensourcedesign/opensourcedesign.github.io/pull/76

I am sorry for not closing this Issue.
Cheers :)

**Comment by RichardLitt** [comment]
No worries. Thanks!
