### ISSUE TITLE
Outdated reference to 'Why open source designers need tools beyond text and code'

### ISSUE THREAD

**Issue by grahamperrin** [opensourcedesign/opensourcedesign.github.io#87]
http://opensourcedesign.net/2015/07/10/this-month-in-open-source-design refers to a blog post by Jan D.: 

- http://opensourcedesign.net/2015/05/23/TextbasedToolsForDesigners.html

That's no longer found. I found it [captured in the Wayback Machine](http://web.archive.org/web/20160326055927/http://opensourcedesign.net/2015/05/23/text-based-tools-for-designers) and re-posted at: 

- [Why designers need tools beyond text and code – Medium
](https://medium.com/@janD/why-designers-need-tools-beyond-text-and-code-405c43a6d5d5)

Please consider an edit to `/2015/07/10/this-month-in-open-source-design` to refer to the Medium address for the post. 

----

Related: https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/_posts/2015-05-24-TextbasedToolsForDesigners.markdown

**Comment by jdittrich** [comment]
It seems to be now at: http://opensourcedesign.net/2015/05/23/text-based-tools-for-designers (as a fix for non-case-sensitive OSes?)

**Comment by simonv3** [comment]
And done, thanks for the fix @jdittrich!
