### ISSUE TITLE
Make "About" page rich with examples

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/opensourcedesign.github.io#9]
Currently, our [About page](http://opensourcedesign.net/about/) outlines the things we hope to achieve with OSD. I really like that it is not a manifesto but more of a list of concrete _actions_ or _resources_

Given the nature of our About page, what if we made each item link to the thing we are working on achieve? Example: 

**"a job board for designers to find open source projects"** 

instead becomes 

**"[a job board](http://opensourcedesign.net/jobs/) for designers to find open source projects"**

This way, a simple reading over our goals also provides examples of our progress / how to participate in said goal :smile:

**Comment by simonv3** [comment]
:+1:

**Comment by RichardLitt** [comment]
I believe this has been done. 

<img width="487" alt="screen shot 2017-03-08 at 9 13 13 am" src="https://cloud.githubusercontent.com/assets/910753/23707199/780b8b84-03df-11e7-8040-25fd15cd4659.png">
